import kotlinx.serialization.Serializable

@Serializable
data class Station(
	val crs: String,
	val name: String
)

object Stations {
	fun getStations(): List<Station> {
		return stations
	}

	fun getStation(crs: String? = null, name: String? = null): Station? {
		if (crs != null) {
			return stations.find { it.crs == crs }
		}

		return stations.find { it.name == name }
	}
}

val stations = listOf(
	Station("AAP", "Alexandra Palace"),
	Station("AAT", "Achanalt"),
	Station("ABA", "Aberdare"),
	Station("ABC", "Altnabreac"),
	Station("ABD", "Aberdeen"),
	Station("ABE", "Aber"),
	Station("ABF", "Ashurst Bald Faced Stag"),
	Station("ABH", "Abererch"),
	Station("ABW", "Abbey Wood"),
	Station("ABY", "Ashburys"),
	Station("ACB", "Acton Bridge"),
	Station("ACC", "Acton Central"),
	Station("ACG", "Acocks Green"),
	Station("ACH", "Achnashellach"),
	Station("ACK", "Acklington"),
	Station("ACL", "Acle"),
	Station("ACN", "Achnasheen"),
	Station("ACR", "Accrington"),
	Station("ACT", "Ascot"),
	Station("ACY", "Abercynon"),
	Station("ADC", "Adlington (Cheshire)"),
	Station("ADD", "Adderley Park"),
	Station("ADK", "Ardwick"),
	Station("ADL", "Adlington (Lancashire)"),
	Station("ADM", "Adisham"),
	Station("ADN", "Ardrossan Town"),
	Station("ADR", "Airdrie"),
	Station("ADS", "Ardrossan Harbour"),
	Station("ADV", "Andover"),
	Station("ADW", "Addiewell"),
	Station("AFK", "Ashford International"),
	Station("AFS", "Ashford (Surrey)"),
	Station("AFV", "Ansdell & Fairhaven"),
	Station("AGL", "Abergele & Pensarn"),
	Station("AGS", "Argyle Street"),
	Station("AGT", "Aldrington"),
	Station("AGV", "Abergavenny"),
	Station("AHD", "Ashtead"),
	Station("AHN", "Ashton-under-Lyne"),
	Station("AHS", "Ashurst (Kent)"),
	Station("AHT", "Aldershot"),
	Station("AHV", "Ash Vale"),
	Station("AIG", "Aigburth"),
	Station("AIN", "Aintree"),
	Station("AIR", "Airbles"),
	Station("ALB", "Albrighton"),
	Station("ALD", "Alderley Edge"),
	Station("ALF", "Alfreton"),
	Station("ALK", "Aslockton"),
	Station("ALM", "Alnmouth"),
	Station("ALN", "Althorne Essex"),
	Station("ALO", "Alloa"),
	Station("ALP", "Althorpe Humber"),
	Station("ALR", "Alresford (Essex)"),
	Station("ALT", "Altrincham"),
	Station("ALV", "Alvechurch"),
	Station("ALW", "Allens West"),
	Station("ALX", "Alexandria"),
	Station("AMB", "Ambergate"),
	Station("AMF", "Ammanford"),
	Station("AML", "Acton Main Line"),
	Station("AMR", "Amersham"),
	Station("AMT", "Aldermaston"),
	Station("AMY", "Amberley"),
	Station("ANC", "Ancaster"),
	Station("AND", "Anderston"),
	Station("ANF", "Ashurst New Forest"),
	Station("ANG", "Angmering"),
	Station("ANL", "Anniesland"),
	Station("ANN", "Annan"),
	Station("ANS", "Ainsdale"),
	Station("ANZ", "Anerley"),
	Station("AON", "Alton"),
	Station("APB", "Appley Bridge"),
	Station("APD", "Appledore (Kent)"),
	Station("APF", "Appleford"),
	Station("APG", "Aspley Guise"),
	Station("APN", "Newcastle Airprt"),
	Station("APP", "Appleby"),
	Station("APS", "Apsley"),
	Station("APY", "Apperley Bridge"),
	Station("ARB", "Arbroath"),
	Station("ARD", "Ardgay"),
	Station("ARG", "Arisaig"),
	Station("ARL", "Arlesey"),
	Station("ARM", "Armadale (West Lothian)"),
	Station("ARN", "Arnside"),
	Station("ARR", "Arram"),
	Station("ART", "Arrochar & Tarbet"),
	Station("ARU", "Arundel"),
	Station("ASB", "Ardrossan South Beach"),
	Station("ASC", "Ashchurch for Tewkesbury"),
	Station("ASF", "Ashfield"),
	Station("ASG", "Alsager"),
	Station("ASH", "Ash"),
	Station("ASK", "Askam"),
	Station("ASN", "Addlestone"),
	Station("ASP", "Aspatria"),
	Station("ASS", "Alness"),
	Station("AST", "Aston"),
	Station("ASY", "Ashley"),
	Station("ATB", "Attenborough"),
	Station("ATH", "Atherstone"),
	Station("ATL", "Attleborough"),
	Station("ATN", "Atherton"),
	Station("ATT", "Attadale"),
	Station("AUD", "Audley End"),
	Station("AUG", "Aughton Park"),
	Station("AUI", "Ardlui"),
	Station("AUK", "Auchinleck"),
	Station("AUR", "Aberdour"),
	Station("AUW", "Ascott-under-Wychwood"),
	Station("AVF", "Avoncliff"),
	Station("AVM", "Aviemore"),
	Station("AVN", "Avonmouth"),
	Station("AVP", "Aylesbury Vale Parkway"),
	Station("AVY", "Aberdovey"),
	Station("AWK", "Adwick"),
	Station("AWM", "Ashwell & Morden"),
	Station("AWT", "Armathwaite"),
	Station("AXM", "Axminster"),
	Station("AXM", "Axminster"),
	Station("AXP", "Alexandra Parade"),
	Station("AYH", "Aylesham"),
	Station("AYL", "Aylesford"),
	Station("AYP", "Albany Park"),
	Station("AYR", "Ayr"),
	Station("AYS", "Aylesbury"),
	Station("AYW", "Aberystwyth"),
	Station("BAA", "Barnham"),
	Station("BAB", "Balcombe"),
	Station("BAC", "Bache"),
	Station("BAD", "Banstead"),
	Station("BAG", "Bagshot"),
	Station("BAH", "Bank Hall"),
	Station("BAI", "Blairhill"),
	Station("BAJ", "Baglan"),
	Station("BAK", "Battersea Park"),
	Station("BAL", "Balham"),
	Station("BAM", "Bamford"),
	Station("BAN", "Banbury"),
	Station("BAR", "Bare Lane"),
	Station("BAS", "Bere Alston"),
	Station("BAT", "Battle"),
	Station("BAU", "Barton-on-Humber"),
	Station("BAV", "Barrow Haven"),
	Station("BAW", "Blackwater"),
	Station("BAY", "Bayford"),
	Station("BBG", "Bishopbriggs"),
	Station("BBK", "Bilbrook"),
	Station("BBL", "Bat & Ball"),
	Station("BBN", "Blackburn"),
	Station("BBS", "Bordesley"),
	Station("BBW", "Berry Brow"),
	Station("BCB", "Burscough Bridge"),
	Station("BCC", "Beccles"),
	Station("BCE", "Bracknell"),
	Station("BCF", "Beaconsfield"),
	Station("BCG", "Birchgrove"),
	Station("BCH", "Birchington-on-Sea"),
	Station("BCJ", "Burscough Junction"),
	Station("BCK", "Buckley"),
	Station("BCN", "Branchton"),
	Station("BCS", "Bicester North"),
	Station("BCU", "Brockenhurst"),
	Station("BCV", "Bruce Grove"),
	Station("BCY", "Brockley"),
	Station("BCZ", "Brent Cross West"),
	Station("BDA", "Brundall"),
	Station("BDB", "Broadbottom"),
	Station("BDG", "Bridgeton"),
	Station("BDH", "Bedhampton"),
	Station("BDH", "Bedhampton"),
	Station("BDI", "Bradford Interchange"),
	Station("BDK", "Baldock"),
	Station("BDL", "Birkdale"),
	Station("BDM", "Bedford"),
	Station("BDN", "Brading"),
	Station("BDQ", "Bradford Forster Square"),
	Station("BDS", "Bond Street El"),
	Station("BDT", "Bridlington"),
	Station("BDW", "Bedwyn"),
	Station("BDY", "Bredbury"),
	Station("BEA", "Bridge of Allan"),
	Station("BEB", "Bebington"),
	Station("BEC", "Beckenham Hill"),
	Station("BEE", "Beeston"),
	Station("BEF", "Benfleet"),
	Station("BEG", "Beltring"),
	Station("BEH", "Bedworth"),
	Station("BEL", "Beauly"),
	Station("BEM", "Bempton"),
	Station("BEN", "Bentham"),
	Station("BEP", "Bermuda Park"),
	Station("BER", "Bearley"),
	Station("BES", "Bescar Lane"),
	Station("BET", "Bethnal Green"),
	Station("BEU", "Beaulieu Road"),
	Station("BEV", "Beverley"),
	Station("BEX", "Bexhill"),
	Station("BEY", "Ben Rhydding"),
	Station("BFD", "Brentford"),
	Station("BFE", "Bere Ferrers"),
	Station("BFF", "Blaenau Ffestiniog"),
	Station("BFN", "Byfleet & New Haw"),
	Station("BFR", "London Blackfriars"),
	Station("BGA", "Brundall Gardens"),
	Station("BGD", "Bargoed"),
	Station("BGE", "Broad Green"),
	Station("BGG", "Brigg"),
	Station("BGH", "Brighouse"),
	Station("BGI", "Bargeddie"),
	Station("BGL", "Bugle"),
	Station("BGM", "Bellingham"),
	Station("BGN", "Bridgend"),
	Station("BGS", "Bogston"),
	Station("BGV", "Barking Riverside"),
	Station("BHA", "Bournmth Air Bus"),
	Station("BHC", "Balloch"),
	Station("BHD", "Brithdir"),
	Station("BHG", "Bathgate"),
	Station("BHI", "Birmingham International"),
	Station("BHK", "Bush Hill Park"),
	Station("BHM", "Birmingham New Street"),
	Station("BHO", "Blackhorse Road"),
	Station("BHR", "Builth Road"),
	Station("BHS", "Brockholes"),
	Station("BIA", "Bishop Auckland"),
	Station("BIC", "Billericay"),
	Station("BID", "Bidston"),
	Station("BIF", "Barrow-in-Furness"),
	Station("BIG", "Billingshurst"),
	Station("BIK", "Birkbeck"),
	Station("BIL", "Billingham"),
	Station("BIN", "Bingham"),
	Station("BIO", "Baillieston"),
	Station("BIP", "Bishopstone"),
	Station("BIS", "Bishops Stortford"),
	Station("BIT", "Bicester Village"),
	Station("BIW", "Biggleswade"),
	Station("BIY", "Bingley"),
	Station("BKA", "Bookham"),
	Station("BKC", "Birkenhead Central"),
	Station("BKD", "Blakedown"),
	Station("BKG", "Barking"),
	Station("BKH", "Blackheath"),
	Station("BKJ", "Beckenham Junction"),
	Station("BKL", "Bickley"),
	Station("BKM", "Berkhamsted"),
	Station("BKN", "Birkenhead North"),
	Station("BKO", "Brookwood"),
	Station("BKP", "Birkenhead Park"),
	Station("BKQ", "Birkenhead Hamilton Square"),
	Station("BKR", "Blackridge"),
	Station("BKS", "Bekesbourne"),
	Station("BKT", "Blake Street"),
	Station("BKW", "Berkswell"),
	Station("BLA", "Blair Atholl"),
	Station("BLB", "Battlesbridge"),
	Station("BLD", "Baildon"),
	Station("BLE", "Bramley (West Yorkshire)"),
	Station("BLG", "Bellgrove"),
	Station("BLH", "Bellshill"),
	Station("BLK", "Blackrod"),
	Station("BLL", "Bardon Mill"),
	Station("BLM", "Belmont"),
	Station("BLN", "Blundellsands & Crosby"),
	Station("BLO", "Blaydon"),
	Station("BLP", "Belper"),
	Station("BLT", "Blantyre"),
	Station("BLV", "Belle Vue"),
	Station("BLW", "Bulwell"),
	Station("BLX", "Bloxwich"),
	Station("BLY", "Bletchley"),
	Station("BMB", "Bamber Bridge"),
	Station("BMC", "Bromley Cross"),
	Station("BMD", "Brimsdown"),
	Station("BME", "Broome"),
	Station("BMF", "Broomfleet"),
	Station("BMG", "Barming"),
	Station("BMH", "Bournemouth"),
	Station("BMK", "Burnham Market"),
	Station("BML", "Bramhall"),
	Station("BMN", "Bromley North"),
	Station("BMO", "Birmingham Moor Street"),
	Station("BMP", "Brampton (Cumbria)"),
	Station("BMR", "Bromborough Rake"),
	Station("BMS", "Bromley South"),
	Station("BMT", "Bedminster"),
	Station("BMV", "Bromsgrove"),
	Station("BMY", "Bramley (Hants)"),
	Station("BNA", "Burnage"),
	Station("BNC", "Burnley Central"),
	Station("BND", "Brandon"),
	Station("BNE", "Bourne End"),
	Station("BNF", "Briton Ferry"),
	Station("BNG", "Bangor (Gwynedd)"),
	Station("BNH", "Barnehurst"),
	Station("BNI", "Barnes Bridge"),
	Station("BNL", "Barnhill"),
	Station("BNM", "Burnham (Bucks)"),
	Station("BNP", "Barnstaple"),
	Station("BNR", "Brockley Whins"),
	Station("BNS", "Barnes"),
	Station("BNT", "Brinnington"),
	Station("BNV", "Banavie"),
	Station("BNW", "Bootle New Strand"),
	Station("BNY", "Barnsley"),
	Station("BOA", "Bradford-on-Avon"),
	Station("BOC", "Bootle (Cumbria)"),
	Station("BOD", "Bodmin Parkway"),
	Station("BOE", "Botley"),
	Station("BOG", "Bognor Regis"),
	Station("BOH", "Bosham"),
	Station("BOM", "Bromborough"),
	Station("BON", "Bolton"),
	Station("BOP", "Bowes Park"),
	Station("BOR", "Bodorgan"),
	Station("BOT", "Bootle Oriel Road"),
	Station("BOW", "Bow Street"),
	Station("BPB", "Blackpool Pleasure Beach"),
	Station("BPK", "Brookmans Park"),
	Station("BPL", "Barlaston Orchard Place"),
	Station("BPN", "Blackpool North"),
	Station("BPO", "Bridport Bus X51"),
	Station("BPS", "Blackpool South"),
	Station("BPT", "Bishopton (Renfrewshire)"),
	Station("BPW", "Bristol Parkway"),
	Station("BRA", "Brora"),
	Station("BRC", "Breich"),
	Station("BRE", "Brentwood"),
	Station("BRF", "Brierfield"),
	Station("BRG", "Borough Green & Wrotham"),
	Station("BRH", "Borth"),
	Station("BRI", "Bristol Temple Meads"),
	Station("BRK", "Berwick (Sussex)"),
	Station("BRL", "Barrhill"),
	Station("BRM", "Barmouth"),
	Station("BRN", "Bearsden"),
	Station("BRO", "Bridge of Orchy"),
	Station("BRP", "Brampton (Suffolk)"),
	Station("BRR", "Barrhead"),
	Station("BRS", "Berrylands"),
	Station("BRT", "Barlaston"),
	Station("BRU", "Bruton"),
	Station("BRV", "Bournville"),
	Station("BRW", "Brunswick"),
	Station("BRX", "Brixton"),
	Station("BRY", "Barry"),
	Station("BSB", "Bleasby"),
	Station("BSC", "Bescot Stadium"),
	Station("BSD", "Bearsted"),
	Station("BSE", "Bury St Edmunds"),
	Station("BSH", "Bushey"),
	Station("BSH", "Bushey"),
	Station("BSI", "Balmossie"),
	Station("BSJ", "Bedford St Johns"),
	Station("BSK", "Basingstoke"),
	Station("BSL", "Beasdale"),
	Station("BSM", "Branksome"),
	Station("BSN", "Boston"),
	Station("BSO", "Basildon"),
	Station("BSP", "Brondesbury Park"),
	Station("BSR", "Broadstairs"),
	Station("BSS", "Barassie"),
	Station("BST", "Bishopstone Hill Rise"),
	Station("BSU", "Brunstane"),
	Station("BSV", "Buckshaw Parkway"),
	Station("BSW", "Birmingham Snow Hill"),
	Station("BSY", "Brondesbury"),
	Station("BTB", "Barnetby"),
	Station("BTD", "Bolton-Upon-Dearne"),
	Station("BTE", "Bitterne"),
	Station("BTF", "Bottesford"),
	Station("BTG", "Barnt Green"),
	Station("BTH", "Bath Spa"),
	Station("BTL", "Batley"),
	Station("BTN", "Brighton"),
	Station("BTO", "Betchworth"),
	Station("BTP", "Braintree Freeport"),
	Station("BTR", "Braintree"),
	Station("BTS", "Burntisland"),
	Station("BTT", "Battersby"),
	Station("BTY", "Bentley (Hants)"),
	Station("BUA", "Bude Bus"),
	Station("BUB", "Burnley Barracks"),
	Station("BUC", "Buckenham"),
	Station("BUD", "Burneside (Cumbria)"),
	Station("BUE", "Bures"),
	Station("BUG", "Burgess Hill"),
	Station("BUH", "Brough"),
	Station("BUI", "Burnside Strathclyde"),
	Station("BUJ", "Burton Joyce"),
	Station("BUK", "Bucknell"),
	Station("BUL", "Butlers Lane"),
	Station("BUO", "Bursledon"),
	Station("BUS", "Busby"),
	Station("BUT", "Burton-on-Trent"),
	Station("BUU", "Burnham-on-Crouch"),
	Station("BUW", "Burley-in-Wharfedale"),
	Station("BUX", "Buxton"),
	Station("BUY", "Burley Park"),
	Station("BVD", "Belvedere"),
	Station("BWB", "Bow Brickhill"),
	Station("BWD", "Birchwood"),
	Station("BWG", "Bowling"),
	Station("BWK", "Berwick-upon-Tweed"),
	Station("BWN", "Bloxwich North"),
	Station("BWO", "Bricket Wood"),
	Station("BWS", "Barrow upon Soar"),
	Station("BWT", "Bridgwater"),
	Station("BXB", "Broxbourne"),
	Station("BXD", "Buxted"),
	Station("BXH", "Bexleyheath"),
	Station("BXW", "Boxhill & Westhumble"),
	Station("BXY", "Bexley"),
	Station("BYA", "Berney Arms"),
	Station("BYB", "Blythe Bridge"),
	Station("BYC", "Betws-y-Coed"),
	Station("BYD", "Barry Docks"),
	Station("BYE", "Bynea"),
	Station("BYF", "Broughty Ferry"),
	Station("BYI", "Barry Island"),
	Station("BYK", "Bentley (South Yorkshire)"),
	Station("BYL", "Barry Links"),
	Station("BYM", "Burnley Manchester Road"),
	Station("BYN", "Bryn"),
	Station("BYS", "Braystones"),
	Station("CAA", "Coventry Arena"),
	Station("CAC", "Caldercruix"),
	Station("CAD", "Cadoxton"),
	Station("CAG", "Carrbridge"),
	Station("CAK", "Cark & Cartmel"),
	Station("CAM", "Camberley"),
	Station("CAN", "Carnoustie"),
	Station("CAO", "Cannock"),
	Station("CAR", "Carlisle"),
	Station("CAS", "Castleton (Manchester)"),
	Station("CAT", "Caterham"),
	Station("CAU", "Causeland"),
	Station("CAY", "Carntyne"),
	Station("CBB", "Carbis Bay"),
	Station("CBC", "Coatbridge Central"),
	Station("CBD", "Conon Bridge"),
	Station("CBE", "Canterbury East"),
	Station("CBG", "Cambridge"),
	Station("CBH", "Cambridge Heath"),
	Station("CBK", "Cranbrook (Devon)"),
	Station("CBL", "Cambuslang"),
	Station("CBN", "Camborne"),
	Station("CBP", "Castle Bar Park"),
	Station("CBR", "Cooksbridge"),
	Station("CBS", "Coatbridge Sunnyside"),
	Station("CBW", "Canterbury West"),
	Station("CBX", "Cameron Bridge"),
	Station("CBY", "Charlbury"),
	Station("CCC", "Criccieth"),
	Station("CCH", "Chichester"),
	Station("CCT", "Cathcart"),
	Station("CDB", "Cardiff Bay"),
	Station("CDD", "Cardenden"),
	Station("CDF", "Cardiff Central"),
	Station("CDI", "Crediton"),
	Station("CDN", "Coulsdon Town"),
	Station("CDO", "Cardonald"),
	Station("CDQ", "Cardiff Queen Street"),
	Station("CDR", "Cardross"),
	Station("CDS", "Coulsdon South"),
	Station("CDT", "Caldicot"),
	Station("CDU", "Cam & Dursley"),
	Station("CDY", "Cartsdyke"),
	Station("CEA", "Cleland"),
	Station("CED", "Cheddington"),
	Station("CEF", "Chapel-en-le-Frith"),
	Station("CEH", "Coleshill Parkway"),
	Station("CEL", "Chelford"),
	Station("CES", "Cressing"),
	Station("CET", "Colchester Town"),
	Station("CEY", "Cononley"),
	Station("CFB", "Catford Bridge"),
	Station("CFC", "Corfe Castle"),
	Station("CFD", "Castleford"),
	Station("CFF", "Croftfoot"),
	Station("CFH", "Chafford Hundred"),
	Station("CFL", "Crossflatts"),
	Station("CFN", "Clifton Down"),
	Station("CFO", "Chalfont & Latimer Und"),
	Station("CFR", "Chandlers Ford"),
	Station("CFT", "Crofton Park"),
	Station("CGD", "Craigendoran"),
	Station("CGM", "Cottingham"),
	Station("CGN", "Cogan"),
	Station("CGW", "Caergwrle"),
	Station("CHC", "Charing Cross (Glasgow)"),
	Station("CHD", "Chesterfield"),
	Station("CHE", "Cheam"),
	Station("CHF", "Church Fenton"),
	Station("CHG", "Charing (Kent)"),
	Station("CHH", "Christs Hospital"),
	Station("CHI", "Chingford"),
	Station("CHK", "Chiswick"),
	Station("CHL", "Chilworth"),
	Station("CHM", "Chelmsford"),
	Station("CHN", "Cheshunt"),
	Station("CHO", "Cholsey"),
	Station("CHP", "Chipstead"),
	Station("CHR", "Christchurch"),
	Station("CHT", "Chathill"),
	Station("CHU", "Cheadle Hulme"),
	Station("CHW", "Chalkwell"),
	Station("CHX", "London Charing Cross"),
	Station("CHY", "Chertsey"),
	Station("CIL", "Chilham"),
	Station("CIM", "Cilmeri"),
	Station("CIR", "Caledonian Road & Barnsbur"),
	Station("CIT", "Chislehurst"),
	Station("CKH", "Corkerhill"),
	Station("CKL", "Corkickle"),
	Station("CKN", "Crewkerne"),
	Station("CKS", "Clarkston"),
	Station("CKT", "Crookston"),
	Station("CKY", "Crosskeys"),
	Station("CLA", "Clandon"),
	Station("CLC", "Castle Cary"),
	Station("CLD", "Chelsfield"),
	Station("CLE", "Cleethorpes"),
	Station("CLG", "Claygate"),
	Station("CLH", "Clitheroe"),
	Station("CLI", "Clifton (Manchester)"),
	Station("CLJ", "Clapham Junction"),
	Station("CLJ", "Clapham Junction"),
	Station("CLJ", "Clapham Junction"),
	Station("CLJ", "Clapham Junction"),
	Station("CLK", "Clock House"),
	Station("CLL", "Collington"),
	Station("CLM", "Collingham"),
	Station("CLN", "Chapeltown (South Yorkshir"),
	Station("CLP", "Clapham High Street"),
	Station("CLR", "Clarbeston Road"),
	Station("CLS", "Chester-le-Street"),
	Station("CLT", "Clacton-On-Sea"),
	Station("CLU", "Carluke"),
	Station("CLV", "Claverdon"),
	Station("CLW", "Chorleywood Und"),
	Station("CLY", "Chinley"),
	Station("CMB", "Cambridge North"),
	Station("CMD", "Camden Road"),
	Station("CME", "Combe (Oxon)"),
	Station("CMF", "Cromford"),
	Station("CMH", "Cwmbach"),
	Station("CML", "Carmyle"),
	Station("CMN", "Carmarthen"),
	Station("CMO", "Camelon"),
	Station("CMR", "Cromer"),
	Station("CMY", "Crossmyloof"),
	Station("CNE", "Colne"),
	Station("CNF", "Carnforth"),
	Station("CNG", "Congleton"),
	Station("CNL", "Canley"),
	Station("CNM", "Cheltenham Spa"),
	Station("CNN", "Canonbury"),
	Station("CNO", "Chetnole"),
	Station("CNP", "Conway Park"),
	Station("CNR", "Crianlarich"),
	Station("CNS", "Conisbrough"),
	Station("CNW", "Conwy"),
	Station("CNY", "Cantley"),
	Station("COA", "Coatdyke"),
	Station("COB", "Cooden Beach"),
	Station("COC", "Cowden Crosroads"),
	Station("COE", "Coombe Junction Halt"),
	Station("COH", "Crowborough"),
	Station("COI", "Crosshill"),
	Station("COL", "Colchester"),
	Station("COM", "Commondale"),
	Station("CON", "Connel Ferry"),
	Station("COO", "Cookham"),
	Station("COP", "Copplestone"),
	Station("COR", "Corby"),
	Station("COS", "Cosford"),
	Station("COT", "Cottingley"),
	Station("COV", "Coventry"),
	Station("COW", "Cowdenbeath"),
	Station("COY", "Coryton"),
	Station("CPA", "Corpach"),
	Station("CPH", "Caerphilly"),
	Station("CPK", "Carpenders Park"),
	Station("CPM", "Chippenham"),
	Station("CPM", "Chippenham"),
	Station("CPN", "Chapelton (Devon)"),
	Station("CPT", "Clapton"),
	Station("CPU", "Capenhurst"),
	Station("CPW", "Chepstow"),
	Station("CPY", "Clapham (North Yorkshire)"),
	Station("CRA", "Cradley Heath"),
	Station("CRB", "Corbridge"),
	Station("CRD", "Chester Road"),
	Station("CRE", "Crewe"),
	Station("CRF", "Carfin"),
	Station("CRG", "Cross Gates"),
	Station("CRH", "Crouch Hill"),
	Station("CRI", "Cricklewood"),
	Station("CRK", "Chirk"),
	Station("CRL", "Chorley"),
	Station("CRM", "Cramlington"),
	Station("CRN", "Crowthorne"),
	Station("CRO", "Croy"),
	Station("CRR", "Corrour"),
	Station("CRS", "Carstairs"),
	Station("CRT", "Chartham"),
	Station("CRV", "Craven Arms"),
	Station("CRW", "Crawley"),
	Station("CRY", "Crayford"),
	Station("CSA", "Cosham"),
	Station("CSB", "Carshalton Beeches"),
	Station("CSD", "Cobham & Stoke D'Abernon"),
	Station("CSG", "Cressington"),
	Station("CSH", "Carshalton"),
	Station("CSK", "Calstock"),
	Station("CSL", "Codsall"),
	Station("CSM", "Castleton Moor"),
	Station("CSN", "Chessington North"),
	Station("CSO", "Croston"),
	Station("CSR", "Chassen Road"),
	Station("CSS", "Chessington South"),
	Station("CST", "London Cannon Street"),
	Station("CSW", "Chestfield & Swalecliffe"),
	Station("CSY", "Coseley"),
	Station("CTE", "Chatelherault"),
	Station("CTF", "Catford"),
	Station("CTH", "Chadwell Heath"),
	Station("CTK", "City Thameslink"),
	Station("CTL", "Cattal"),
	Station("CTM", "Chatham"),
	Station("CTN", "Charlton"),
	Station("CTO", "Carlton"),
	Station("CTR", "Chester"),
	Station("CTT", "Church Stretton"),
	Station("CTW", "Church & Oswaldtwistle"),
	Station("CUA", "Culrain"),
	Station("CUB", "Cumbernauld"),
	Station("CUD", "Cuddington"),
	Station("CUF", "Cuffley"),
	Station("CUH", "Curriehill"),
	Station("CUM", "Culham"),
	Station("CUP", "Cupar"),
	Station("CUS", "Custom House El"),
	Station("CUW", "Clunderwen"),
	Station("CUX", "Cuxton"),
	Station("CWB", "Colwyn Bay"),
	Station("CWC", "Chappel & Wakes Colne"),
	Station("CWD", "Creswell"),
	Station("CWE", "Crowle"),
	Station("CWH", "Crews Hill"),
	Station("CWL", "Colwall"),
	Station("CWM", "Cwmbran"),
	Station("CWN", "Cowden"),
	Station("CWS", "Caersws"),
	Station("CWU", "Crowhurst"),
	Station("CWX", "Canary Wharf El"),
	Station("CYB", "Cefn-y-Bedd"),
	Station("CYK", "Clydebank"),
	Station("CYN", "Cynghordy"),
	Station("CYP", "Crystal Palace"),
	Station("CYS", "Cathays"),
	Station("CYT", "Cherry Tree"),
	Station("DAG", "Dalgety Bay"),
	Station("DAK", "Dalmarnock"),
	Station("DAL", "Dalmally"),
	Station("DAM", "Dalmeny"),
	Station("DAN", "Darnall"),
	Station("DAR", "Darlington"),
	Station("DAT", "Datchet"),
	Station("DBC", "Dumbarton Central"),
	Station("DBD", "Denby Dale"),
	Station("DBE", "Dumbarton East"),
	Station("DBG", "Mottisfont & Dunbridge"),
	Station("DBL", "Dunblane"),
	Station("DBR", "Derby Road (Ipswich)"),
	Station("DBY", "Derby"),
	Station("DCG", "Duncraig"),
	Station("DCH", "Dorchester South"),
	Station("DCT", "Danescourt"),
	Station("DCW", "Dorchester West"),
	Station("DDG", "Dorridge"),
	Station("DDK", "Dagenham Dock"),
	Station("DDP", "Dudley Port"),
	Station("DEA", "Deal"),
	Station("DEE", "Dundee"),
	Station("DEN", "Dean"),
	Station("DEP", "Deptford"),
	Station("DEW", "Dewsbury"),
	Station("DFD", "Dartford"),
	Station("DFE", "Dunfermline City"),
	Station("DFI", "Duffield"),
	Station("DFL", "Dunfermline Queen Margaret"),
	Station("DFR", "Drumfrochar"),
	Station("DGC", "Denham Golf Club"),
	Station("DGL", "Dingle Road"),
	Station("DGT", "Deansgate"),
	Station("DGY", "Deganwy"),
	Station("DHM", "Durham"),
	Station("DHN", "Deighton"),
	Station("DID", "Didcot Parkway"),
	Station("DIG", "Digby & Sowton"),
	Station("DIN", "Dingwall"),
	Station("DIS", "Diss"),
	Station("DKD", "Dunkeld & Birnam"),
	Station("DKG", "Dorking"),
	Station("DKT", "Dorking West"),
	Station("DLG", "Dolgarrog"),
	Station("DLH", "Doleham"),
	Station("DLJ", "Dalston Junction"),
	Station("DLK", "Dalston Kingsland"),
	Station("DLM", "Delamere"),
	Station("DLR", "Dalreoch"),
	Station("DLS", "Dalston (Cumbria)"),
	Station("DLT", "Dalton"),
	Station("DLW", "Dalwhinnie"),
	Station("DLY", "Dalry"),
	Station("DMC", "Drumchapel"),
	Station("DMF", "Dumfries"),
	Station("DMG", "Dinas (Rhondda)"),
	Station("DMH", "Dilton Marsh"),
	Station("DMK", "Denmark Hill"),
	Station("DMP", "Dumpton Park"),
	Station("DMR", "Dalmuir"),
	Station("DMS", "Dormans"),
	Station("DMY", "Drumry"),
	Station("DND", "Dinsdale"),
	Station("DNG", "Dunton Green"),
	Station("DNL", "Dunlop"),
	Station("DNM", "Denham"),
	Station("DNO", "Dunrobin Castle"),
	Station("DNS", "Dinas Powys"),
	Station("DNT", "Dent"),
	Station("DNY", "Danby"),
	Station("DOC", "Dockyard (Devonport)"),
	Station("DOD", "Dodworth"),
	Station("DOL", "Dolau"),
	Station("DON", "Doncaster"),
	Station("DOR", "Dore & Totley"),
	Station("DOT", "Dunston"),
	Station("DOW", "Downham Market"),
	Station("DPD", "Dorking Deepdene"),
	Station("DPT", "Devonport"),
	Station("DPT", "Devonport"),
	Station("DRF", "Driffield"),
	Station("DRG", "Drayton Green"),
	Station("DRI", "Drigg"),
	Station("DRM", "Drem"),
	Station("DRN", "Duirinish"),
	Station("DRO", "Dronfield"),
	Station("DRT", "Darton"),
	Station("DRU", "Drumgelloch"),
	Station("DSL", "Disley"),
	Station("DSM", "Darsham"),
	Station("DST", "Duke Street"),
	Station("DSY", "Daisy Hill"),
	Station("DTG", "Dinting"),
	Station("DTN", "Denton"),
	Station("DTW", "Droitwich Spa"),
	Station("DUD", "Duddeston"),
	Station("DUL", "Dullingham"),
	Station("DUM", "Dumbreck"),
	Station("DUN", "Dunbar"),
	Station("DUR", "Durrington-on-Sea"),
	Station("DVC", "Dovercourt"),
	Station("DVH", "Dove Holes"),
	Station("DVN", "Davenport"),
	Station("DVP", "Dover Priory"),
	Station("DVY", "Dovey Junction"),
	Station("DWD", "Dolwyddelan"),
	Station("DWL", "Dawlish"),
	Station("DWN", "Darwen"),
	Station("DWW", "Dawlish Warren"),
	Station("DYC", "Dyce"),
	Station("DYF", "Dyffryn Ardudwy"),
	Station("DYP", "Drayton Park"),
	Station("DZY", "Danzey"),
	Station("EAD", "Earlsfield"),
	Station("EAG", "Eaglescliffe"),
	Station("EAL", "Ealing Broadway"),
	Station("EAR", "Earley"),
	Station("EBA", "Euxton Balshaw Lane"),
	Station("EBB", "Ebbw Vale Town"),
	Station("EBD", "Ebbsfleet International"),
	Station("EBK", "Eastbrook"),
	Station("EBL", "East Boldon"),
	Station("EBN", "Eastbourne"),
	Station("EBR", "Edenbridge"),
	Station("EBT", "Edenbridge Town"),
	Station("EBV", "Ebbw Vale Parkway"),
	Station("ECC", "Eccles"),
	Station("ECL", "Eccleston Park"),
	Station("ECP", "Energlyn & Churchill Park"),
	Station("ECR", "East Croydon"),
	Station("ECS", "Eccles Road"),
	Station("EDB", "Edinburgh"),
	Station("EDG", "Edge Hill"),
	Station("EDL", "Edale"),
	Station("EDN", "Eden Park"),
	Station("EDP", "Edinburgh Park"),
	Station("EDR", "Edmonton Green"),
	Station("EDW", "East Dulwich"),
	Station("EDY", "East Didsbury"),
	Station("EFF", "Effingham Junction"),
	Station("EFL", "East Farleigh"),
	Station("EGF", "East Garforth"),
	Station("EGG", "Eggesford"),
	Station("EGH", "Egham"),
	Station("EGN", "Eastrington"),
	Station("EGR", "East Grinstead"),
	Station("EGT", "Egton"),
	Station("EGY", "Edinburgh Gateway"),
	Station("EKB", "Eskbank"),
	Station("EKL", "East Kilbride"),
	Station("ELD", "Earlswood (Surrey)"),
	Station("ELE", "Elmers End"),
	Station("ELG", "Elgin"),
	Station("ELO", "Elton & Orston"),
	Station("ELP", "Ellesmere Port"),
	Station("ELR", "Elsecar"),
	Station("ELS", "Elstree & Borehamwood"),
	Station("ELT", "East Linton"),
	Station("ELW", "Eltham"),
	Station("ELY", "Ely"),
	Station("EMA", "East M Air/Dby"),
	Station("EMD", "East Midlands Parkway"),
	Station("EML", "East Malling"),
	Station("EMP", "Emerson Park"),
	Station("EMS", "Emsworth"),
	Station("ENC", "Enfield Chase"),
	Station("ENF", "Enfield Town"),
	Station("ENL", "Enfield Lock"),
	Station("ENT", "Entwistle"),
	Station("EPD", "Epsom Downs"),
	Station("EPH", "Elephant & Castle"),
	Station("EPS", "Epsom"),
	Station("ERA", "Eastham Rake"),
	Station("ERB", "Eridge A26 Bus S"),
	Station("ERD", "Erdington"),
	Station("ERH", "Erith"),
	Station("ERI", "Eridge"),
	Station("ERL", "Earlestown"),
	Station("ESD", "Elmstead Woods"),
	Station("ESH", "Esher"),
	Station("ESL", "Eastleigh"),
	Station("ESM", "Elsenham"),
	Station("EST", "Easterhouse"),
	Station("ESW", "Elmswell"),
	Station("ETC", "Etchingham"),
	Station("ETL", "East Tilbury"),
	Station("EUS", "London Euston"),
	Station("EVE", "Evesham"),
	Station("EWD", "Earlswood (West Midlands)"),
	Station("EWE", "Ewell East"),
	Station("EWR", "East Worthing"),
	Station("EWW", "Ewell West"),
	Station("EXC", "Exeter Central"),
	Station("EXD", "Exeter St Davids"),
	Station("EXG", "Exhibition Centre (Glasgow"),
	Station("EXM", "Exmouth"),
	Station("EXN", "Exton"),
	Station("EXR", "Essex Road"),
	Station("EXT", "Exeter St Thomas"),
	Station("EYN", "Eynsford"),
	Station("FAL", "Falmouth Docks"),
	Station("FAV", "Faversham"),
	Station("FAZ", "Fazakerley"),
	Station("FBY", "Formby"),
	Station("FCN", "Falconwood"),
	Station("FEA", "Featherstone"),
	Station("FEG", "Fellgate Metro"),
	Station("FEL", "Feltham"),
	Station("FEN", "Fenny Stratford"),
	Station("FER", "Fernhill"),
	Station("FFA", "Ffairfach"),
	Station("FFD", "Freshford"),
	Station("FGH", "Fishguard Harbour"),
	Station("FGT", "Faygate"),
	Station("FGW", "Fishguard & Goodwick"),
	Station("FIL", "Filey"),
	Station("FIN", "Finstock"),
	Station("FIT", "Filton Abbey Wood"),
	Station("FKC", "Folkestone Central"),
	Station("FKG", "Falkirk Grahamston"),
	Station("FKK", "Falkirk High"),
	Station("FKW", "Folkestone West"),
	Station("FLD", "Fauldhouse"),
	Station("FLE", "Fleet"),
	Station("FLF", "Flowery Field"),
	Station("FLI", "Flixton"),
	Station("FLM", "Flimby"),
	Station("FLN", "Flint"),
	Station("FLT", "Flitwick"),
	Station("FLW", "Fulwell"),
	Station("FLX", "Felixstowe"),
	Station("FML", "Frimley"),
	Station("FMR", "Falmer"),
	Station("FMT", "Falmouth Town"),
	Station("FNB", "Farnborough (Main)"),
	Station("FNC", "Farncombe"),
	Station("FNH", "Farnham"),
	Station("FNN", "Farnborough North"),
	Station("FNR", "Farningham Road"),
	Station("FNT", "Feniton"),
	Station("FNV", "Furness Vale"),
	Station("FNW", "Farnworth"),
	Station("FNY", "Finchley Road & Frognal"),
	Station("FOC", "Falls of Cruachan"),
	Station("FOD", "Ford"),
	Station("FOG", "Forest Gate"),
	Station("FOH", "Forest Hill"),
	Station("FOK", "Four Oaks"),
	Station("FOR", "Forres"),
	Station("FOX", "Foxfield"),
	Station("FPK", "Finsbury Park"),
	Station("FRB", "Fairbourne"),
	Station("FRD", "Frodsham"),
	Station("FRE", "Freshfield"),
	Station("FRF", "Fairfield"),
	Station("FRI", "Frinton-On-Sea"),
	Station("FRL", "Fairlie"),
	Station("FRM", "Fareham"),
	Station("FRN", "Fearn"),
	Station("FRO", "Frome"),
	Station("FRS", "Forsinard"),
	Station("FRT", "Frant"),
	Station("FRW", "Fairwater"),
	Station("FRY", "Ferriby"),
	Station("FSB", "Fishbourne (Sussex)"),
	Station("FSG", "Fishersgate"),
	Station("FSK", "Fiskerton"),
	Station("FST", "London Fenchurch Street"),
	Station("FTM", "Fort Matilda"),
	Station("FTN", "Fratton"),
	Station("FTW", "Fort William"),
	Station("FWY", "Five Ways"),
	Station("FXN", "Foxton"),
	Station("FYS", "Ferryside"),
	Station("FZH", "Frizinghall"),
	Station("FZP", "Furze Platt"),
	Station("FZW", "Fitzwilliam"),
	Station("GAL", "Galashiels"),
	Station("GAR", "Garrowhill"),
	Station("GBD", "Gilberdyke"),
	Station("GBG", "Gorebridge"),
	Station("GBK", "Greenbank"),
	Station("GBL", "Gainsborough Lea Road"),
	Station("GBS", "Goring-by-Sea"),
	Station("GCH", "Garelochhead"),
	Station("GCR", "Gloucester"),
	Station("GCT", "Great Coates"),
	Station("GCW", "Glan Conwy"),
	Station("GDH", "Gordon Hill"),
	Station("GDL", "Godley"),
	Station("GDN", "Godstone"),
	Station("GDP", "Gidea Park"),
	Station("GEA", "Gretna Green"),
	Station("GER", "Gerrards Cross"),
	Station("GFD", "Greenford"),
	Station("GFF", "Gilfach Fargoed"),
	Station("GFN", "Giffnock"),
	Station("GGJ", "Georgemas Junction"),
	Station("GGT", "Glasgow Airport"),
	Station("GGV", "Gargrave"),
	Station("GIG", "Giggleswick"),
	Station("GIL", "Gillingham (Dorset)"),
	Station("GIP", "Gipsy Hill"),
	Station("GIR", "Girvan"),
	Station("GKC", "Greenock Central"),
	Station("GKW", "Greenock West"),
	Station("GLC", "Glasgow Central"),
	Station("GLC", "Glasgow Cent Ll"),
	Station("GLD", "Guildford"),
	Station("GLE", "Gleneagles"),
	Station("GLF", "Glenfinnan"),
	Station("GLG", "Glengarnock"),
	Station("GLH", "Glasshoughton"),
	Station("GLM", "Gillingham (Kent)"),
	Station("GLO", "Glossop"),
	Station("GLQ", "Glasgow Queen Street"),
	Station("GLQ", "Glasgow Qs Ll"),
	Station("GLS", "Glaisdale"),
	Station("GLT", "Glenrothes With Thornton"),
	Station("GLY", "Glynde"),
	Station("GLZ", "Glazebrook"),
	Station("GMB", "Grimsby Town"),
	Station("GMD", "Grimsby Docks"),
	Station("GMG", "Garth (Bridgend)"),
	Station("GMN", "Great Missenden"),
	Station("GMT", "Grosmont"),
	Station("GMV", "Great Malvern"),
	Station("GMY", "Goodmayes"),
	Station("GNB", "Gainsborough Central"),
	Station("GNF", "Greenfield"),
	Station("GNH", "Greenhithe for Bluewater"),
	Station("GNL", "Green Lane"),
	Station("GNR", "Green Road"),
	Station("GNT", "Gunton"),
	Station("GNW", "Greenwich"),
	Station("GOB", "Gobowen"),
	Station("GOD", "Godalming"),
	Station("GOE", "Goldthorpe"),
	Station("GOF", "Golf Street"),
	Station("GOL", "Golspie"),
	Station("GOM", "Gomshall"),
	Station("GOO", "Goole"),
	Station("GOR", "Goring & Streatley"),
	Station("GOS", "Grange-over-Sands"),
	Station("GOX", "Goxhill"),
	Station("GPK", "Grange Park"),
	Station("GPO", "Gospel Oak"),
	Station("GRA", "Grantham"),
	Station("GRB", "Great Bentley"),
	Station("GRC", "Great Chesterford"),
	Station("GRF", "Garforth"),
	Station("GRH", "Gartcosh"),
	Station("GRK", "Gourock"),
	Station("GRL", "Greenfaulds"),
	Station("GRN", "Grindleford"),
	Station("GRP", "Grove Park"),
	Station("GRS", "Garscadden"),
	Station("GRT", "Grateley"),
	Station("GRV", "Gravesend"),
	Station("GRY", "Grays"),
	Station("GSC", "Gilshochill"),
	Station("GSD", "Garsdale"),
	Station("GSL", "Gunnislake"),
	Station("GSN", "Garston (Herts)"),
	Station("GST", "Gathurst"),
	Station("GSW", "Garswood"),
	Station("GSY", "Guiseley"),
	Station("GTA", "Great Ayton"),
	Station("GTH", "Garth (Powys)"),
	Station("GTN", "Grangetown (Cardiff)"),
	Station("GTO", "Gorton"),
	Station("GTR", "Goostrey"),
	Station("GTW", "Gatwick Airport"),
	Station("GTY", "Gatley"),
	Station("GUI", "Guide Bridge"),
	Station("GUN", "Gunnersbury"),
	Station("GVE", "Garve"),
	Station("GVH", "Gravelly Hill"),
	Station("GWE", "Gwersyllt"),
	Station("GWN", "Gowerton"),
	Station("GYM", "Great Yarmouth"),
	Station("GYP", "Gypsy Lane"),
	Station("HAB", "Habrough"),
	Station("HAC", "Hackney Downs"),
	Station("HAD", "Haddiscoe"),
	Station("HAF", "Heathrow Terminal 4X"),
	Station("HAG", "Hagley"),
	Station("HAI", "Halling"),
	Station("HAL", "Hale"),
	Station("HAM", "Hamworthy"),
	Station("HAN", "Hanwell"),
	Station("HAP", "Hatfield Peverel"),
	Station("HAS", "Halesworth"),
	Station("HAT", "Hatfield (Herts)"),
	Station("HAV", "Havant"),
	Station("HAY", "Hayes & Harlington"),
	Station("HAZ", "Hazel Grove"),
	Station("HBB", "Hubberts Bridge"),
	Station("HBD", "Hebden Bridge"),
	Station("HBF", "Hever Brocasfarm"),
	Station("HBL", "Headbolt Lane"),
	Station("HBN", "Hollingbourne"),
	Station("HBP", "Hornbeam Park"),
	Station("HBY", "Hartlebury"),
	Station("HCB", "Hackbridge"),
	Station("HCH", "Holmes Chapel"),
	Station("HCN", "Headcorn"),
	Station("HCT", "Huncoat"),
	Station("HDB", "Haydon Bridge"),
	Station("HDE", "Hedge End"),
	Station("HDF", "Hadfield"),
	Station("HDG", "Heald Green"),
	Station("HDH", "Hampstead Heath"),
	Station("HDL", "Headstone Lane"),
	Station("HDM", "Haddenham & Thame Parkway"),
	Station("HDN", "Harlesden"),
	Station("HDW", "Hadley Wood"),
	Station("HDY", "Headingley"),
	Station("HEC", "Heckington"),
	Station("HED", "Halewood"),
	Station("HEI", "Heighington"),
	Station("HEL", "Hensall"),
	Station("HEN", "Hendon"),
	Station("HER", "Hersham"),
	Station("HES", "Hessle"),
	Station("HEV", "Hever"),
	Station("HEW", "Heworth"),
	Station("HEX", "Hexham"),
	Station("HFD", "Hereford"),
	Station("HFE", "Hertford East"),
	Station("HFN", "Hertford North"),
	Station("HFS", "Hatfield & Stainforth"),
	Station("HFX", "Halifax"),
	Station("HGD", "Hungerford"),
	Station("HGF", "Hag Fold"),
	Station("HGG", "Haggerston"),
	Station("HGM", "Higham"),
	Station("HGN", "Hough Green"),
	Station("HGR", "Hither Green"),
	Station("HGS", "Hastings"),
	Station("HGT", "Harrogate"),
	Station("HGY", "Harringay"),
	Station("HHB", "Heysham Port"),
	Station("HHD", "Holyhead"),
	Station("HHE", "Haywards Heath"),
	Station("HHL", "Heath High Level"),
	Station("HHY", "Highbury & Islington"),
	Station("HHY", "Highbury & Islington Nll"),
	Station("HIA", "Hampton-in-Arden"),
	Station("HIB", "High Brooms"),
	Station("HID", "Hall-I'-Th'-Wood"),
	Station("HIG", "Highbridge & Burnham"),
	Station("HIL", "Hillside"),
	Station("HIN", "Hindley"),
	Station("HIP", "Highams Park"),
	Station("HIR", "Horton-In-Ribblesdale"),
	Station("HIT", "Hitchin"),
	Station("HKC", "Hackney Central"),
	Station("HKH", "Hawkhead"),
	Station("HKM", "Hykeham"),
	Station("HKN", "Hucknall"),
	Station("HKW", "Hackney Wick"),
	Station("HLB", "Hildenborough"),
	Station("HLC", "Helensburgh Central"),
	Station("HLD", "Hellifield"),
	Station("HLE", "Hillington East"),
	Station("HLF", "Hillfoot"),
	Station("HLG", "Hall Green"),
	Station("HLI", "Healing"),
	Station("HLL", "Heath Low Level"),
	Station("HLM", "Holmwood"),
	Station("HLN", "Harlington (Bedfordshire)"),
	Station("HLR", "Hall Road"),
	Station("HLS", "Hilsea"),
	Station("HLU", "Helensburgh Upper"),
	Station("HLW", "Hillington West"),
	Station("HLY", "Holytown"),
	Station("HMC", "Hampton Court"),
	Station("HMD", "Hampden Park (Sussex)"),
	Station("HME", "Hamble"),
	Station("HML", "Hemel Hempstead"),
	Station("HMM", "Hammerton"),
	Station("HMN", "Homerton"),
	Station("HMP", "Hampton (London)"),
	Station("HMS", "Helmsdale"),
	Station("HMT", "Ham Street"),
	Station("HMW", "Hampton Wick"),
	Station("HMY", "Hairmyres"),
	Station("HNA", "Hinton Admiral"),
	Station("HNB", "Herne Bay"),
	Station("HNC", "Hamilton Central"),
	Station("HND", "Hanborough"),
	Station("HNF", "Hednesford"),
	Station("HNG", "Hengoed"),
	Station("HNH", "Herne Hill"),
	Station("HNK", "Hinckley"),
	Station("HNL", "Henley-in-Arden"),
	Station("HNT", "Huntly"),
	Station("HNW", "Hamilton West"),
	Station("HNX", "Hunts Cross"),
	Station("HOC", "Hockley"),
	Station("HOH", "Harrow-on-the-Hill"),
	Station("HOK", "Hook"),
	Station("HOL", "Holton Heath"),
	Station("HON", "Honiton"),
	Station("HON", "Honiton"),
	Station("HOO", "Hooton"),
	Station("HOP", "Hope (Derbyshire)"),
	Station("HOR", "Horley"),
	Station("HOT", "Henley-on-Thames"),
	Station("HOU", "Hounslow"),
	Station("HOV", "Hove"),
	Station("HOW", "Howden"),
	Station("HOX", "Hoxton"),
	Station("HOY", "Honley"),
	Station("HOZ", "Howwood (Renfrew)"),
	Station("HPA", "Honor Oak Park"),
	Station("HPD", "Harpenden"),
	Station("HPE", "Hope (Flintshire)"),
	Station("HPL", "Hartlepool"),
	Station("HPN", "Hapton"),
	Station("HPQ", "Harwich International"),
	Station("HPT", "Hopton Heath"),
	Station("HRD", "Harling Road"),
	Station("HRE", "Horden"),
	Station("HRH", "Horsham"),
	Station("HRL", "Harlech"),
	Station("HRM", "Harrietsham"),
	Station("HRN", "Hornsey"),
	Station("HRO", "Harold Wood"),
	Station("HRR", "Harrington"),
	Station("HRS", "Horsforth"),
	Station("HRW", "Harrow & Wealdstone"),
	Station("HRW", "Harrow & Wealdstone"),
	Station("HRY", "Harringay Green Lanes"),
	Station("HSB", "Helsby"),
	Station("HSC", "Hoscar"),
	Station("HSD", "Hamstead (Birmingham)"),
	Station("HSG", "Hathersage"),
	Station("HSK", "Hassocks"),
	Station("HSL", "Haslemere"),
	Station("HST", "High Street (Glasgow)"),
	Station("HSW", "Heswall"),
	Station("HSY", "Horsley"),
	Station("HTC", "Heaton Chapel"),
	Station("HTE", "Hatch End"),
	Station("HTF", "Hartford (Cheshire)"),
	Station("HTH", "Handforth"),
	Station("HTN", "Hatton"),
	Station("HTO", "Hightown"),
	Station("HTW", "Hartwood"),
	Station("HTY", "Hattersley"),
	Station("HUB", "Hunmanby"),
	Station("HUD", "Huddersfield"),
	Station("HUL", "Hull"),
	Station("HUN", "Huntingdon"),
	Station("HUP", "Humphrey Park"),
	Station("HUR", "Hurst Green"),
	Station("HUS", "Hunstanton Bus"),
	Station("HUT", "Hutton Cranswick"),
	Station("HUY", "Huyton"),
	Station("HVF", "Haverfordwest"),
	Station("HVN", "Havenhouse"),
	Station("HWB", "Hawarden Bridge"),
	Station("HWC", "Harwich Town"),
	Station("HWD", "Hawarden"),
	Station("HWH", "Haltwhistle"),
	Station("HWI", "Horwich Parkway"),
	Station("HWM", "Harlow Mill"),
	Station("HWN", "Harlow Town"),
	Station("HWV", "Heathrow Terminal 5"),
	Station("HWW", "How Wood (Hertfordshire)"),
	Station("HWY", "High Wycombe"),
	Station("HXM", "Hoveton & Wroxham"),
	Station("HXX", "Heathrow Terminals 2 & 3"),
	Station("HYB", "Honeybourne"),
	Station("HYC", "Hyde Central"),
	Station("HYD", "Heyford"),
	Station("HYH", "Hythe (Essex)"),
	Station("HYK", "Hoylake"),
	Station("HYL", "Hayle"),
	Station("HYM", "Haymarket"),
	Station("HYN", "Hyndland"),
	Station("HYR", "Haydons Road"),
	Station("HYS", "Hayes (Kent)"),
	Station("HYT", "Hyde North"),
	Station("HYW", "Hinchley Wood"),
	Station("IFD", "Ilford"),
	Station("IFI", "Ifield"),
	Station("IGD", "Invergordon"),
	Station("ILK", "Ilkley"),
	Station("ILN", "Ilkeston"),
	Station("IMW", "Imperial Wharf"),
	Station("INB", "Inverness Airport Bus Stan"),
	Station("INC", "Ince (Manchester)"),
	Station("INE", "Ince & Elton"),
	Station("ING", "Invergowrie"),
	Station("INH", "Invershin"),
	Station("INK", "Inverkeithing"),
	Station("INP", "Inverkip"),
	Station("INR", "Inverurie"),
	Station("INS", "Insch"),
	Station("INT", "Ingatestone"),
	Station("INV", "Inverness"),
	Station("IPS", "Ipswich"),
	Station("IRL", "Irlam"),
	Station("IRV", "Irvine"),
	Station("ISL", "Isleworth"),
	Station("ISP", "Islip"),
	Station("IVA", "Inverness Airport"),
	Station("IVR", "Iver"),
	Station("IVY", "Ivybridge"),
	Station("JCH", "James Cook University Hosp"),
	Station("JEQ", "Jewellery Quarter"),
	Station("JHN", "Johnstone (Renfrewshire)"),
	Station("JOH", "Johnston (Pembs)"),
	Station("JOR", "Jordanhill"),
	Station("KBC", "Kinbrace"),
	Station("KBF", "Kirkby-in-Furness"),
	Station("KBK", "Kents Bank"),
	Station("KBN", "Kilburn High Road"),
	Station("KBW", "Knebworth"),
	Station("KBX", "Kirby Cross"),
	Station("KCK", "Knockholt"),
	Station("KDB", "Kidbrooke"),
	Station("KDG", "Kidsgrove"),
	Station("KDY", "Kirkcaldy"),
	Station("KEH", "Keith"),
	Station("KEI", "Keighley"),
	Station("KEL", "Kelvedon"),
	Station("KEM", "Kemble"),
	Station("KEN", "Kendal"),
	Station("KET", "Kettering"),
	Station("KEY", "Keyham"),
	Station("KGE", "Kingsknowe"),
	Station("KGH", "Kinghorn"),
	Station("KGL", "Kings Langley"),
	Station("KGM", "Kingham"),
	Station("KGN", "Kings Nympton"),
	Station("KGP", "Kings Park"),
	Station("KGS", "Kings Sutton"),
	Station("KGT", "Kilgetty"),
	Station("KGX", "London Kings Cross"),
	Station("KID", "Kidderminster"),
	Station("KIL", "Kildonan"),
	Station("KIN", "Kingussie"),
	Station("KIR", "Kirkby (Merseyside)"),
	Station("KIT", "Kintbury"),
	Station("KIV", "Kiveton Bridge"),
	Station("KKB", "Kirkby-In-Ashfield"),
	Station("KKD", "Kirkdale"),
	Station("KKH", "Kirkhill"),
	Station("KKM", "Kirkham & Wesham"),
	Station("KKN", "Kirknewton"),
	Station("KKS", "Kirk Sandall"),
	Station("KLD", "Kildale"),
	Station("KLF", "Kirkstall Forge"),
	Station("KLM", "Kilmaurs"),
	Station("KLN", "Kings Lynn"),
	Station("KLY", "Kenley"),
	Station("KMH", "Kempston Hardwick"),
	Station("KMK", "Kilmarnock"),
	Station("KML", "Kemsley"),
	Station("KMP", "Kempton Park"),
	Station("KMS", "Kemsing"),
	Station("KNA", "Knaresborough"),
	Station("KND", "Kingswood"),
	Station("KNE", "Kennett"),
	Station("KNF", "Knutsford"),
	Station("KNG", "Kingston"),
	Station("KNI", "Knighton"),
	Station("KNL", "Kensal Green"),
	Station("KNN", "Kings Norton"),
	Station("KNO", "Knottingley"),
	Station("KNR", "Kensal Rise"),
	Station("KNS", "Kennishead"),
	Station("KNT", "Kenton"),
	Station("KNU", "Knucklas"),
	Station("KNW", "Kenilworth"),
	Station("KNW", "Kenilworth"),
	Station("KNW", "Kenilworth"),
	Station("KPA", "Kensington Olympia"),
	Station("KPT", "Kilpatrick"),
	Station("KRK", "Kirkconnel"),
	Station("KSL", "Kearsley"),
	Station("KSN", "Kearsney"),
	Station("KSW", "Kirkby Stephen"),
	Station("KTH", "Kent House"),
	Station("KTL", "Kirton Lindsey"),
	Station("KTN", "Kentish Town"),
	Station("KTR", "Kintore"),
	Station("KTW", "Kentish Town West"),
	Station("KVD", "Kelvindale"),
	Station("KVP", "Kiveton Park"),
	Station("KWB", "Kew Bridge"),
	Station("KWD", "Kirkwood"),
	Station("KWG", "Kew Gardens"),
	Station("KWL", "Kidwelly"),
	Station("KWN", "Kilwinning"),
	Station("KWR", "Kingswear (For Dartmouth)"),
	Station("KYL", "Kyle of Lochalsh"),
	Station("KYN", "Keynsham"),
	Station("LAC", "Lancing"),
	Station("LAD", "Ladywell"),
	Station("LAG", "Langwith - Whaley Thorns"),
	Station("LAI", "Laindon"),
	Station("LAK", "Lakenheath"),
	Station("LAM", "Lamphey"),
	Station("LAN", "Lancaster"),
	Station("LAP", "Lapford"),
	Station("LAR", "Largs"),
	Station("LAS", "Llansamlet"),
	Station("LAU", "Laurencekirk"),
	Station("LAW", "Landywood"),
	Station("LAY", "Layton (Lancs)"),
	Station("LBG", "London Bridge"),
	Station("LBG", "London Bridge"),
	Station("LBK", "Long Buckby"),
	Station("LBO", "Loughborough"),
	Station("LBR", "Llanbedr"),
	Station("LBT", "Larbert"),
	Station("LBZ", "Leighton Buzzard"),
	Station("LCC", "Lochluichart"),
	Station("LCG", "Lochgelly"),
	Station("LCK", "Lockwood"),
	Station("LCL", "Lochailort"),
	Station("LCN", "Lincoln"),
	Station("LCS", "Locheilside"),
	Station("LDN", "Llandanwg"),
	Station("LDS", "Leeds"),
	Station("LDY", "Ladybank"),
	Station("LEA", "Leagrave"),
	Station("LEB", "Lea Bridge"),
	Station("LED", "Ledbury"),
	Station("LEE", "Lee (London)"),
	Station("LEG", "Lea Green"),
	Station("LEH", "Lea Hall"),
	Station("LEI", "Leicester"),
	Station("LEL", "Lelant"),
	Station("LEM", "Leyton Midland Road"),
	Station("LEN", "Lenham"),
	Station("LEO", "Leominster"),
	Station("LER", "Leytonstone High Road"),
	Station("LES", "Leigh-on-Sea"),
	Station("LET", "Letchworth Garden City"),
	Station("LEU", "Leuchars"),
	Station("LEV", "Leven"),
	Station("LEW", "Lewisham"),
	Station("LEY", "Leyland"),
	Station("LFD", "Lingfield"),
	Station("LGB", "Langbank"),
	Station("LGD", "Lingwood"),
	Station("LGE", "Long Eaton"),
	Station("LGF", "Longfield"),
	Station("LGG", "Langley Green"),
	Station("LGJ", "Loughborough Junction"),
	Station("LGK", "Longbeck"),
	Station("LGM", "Langley Mill"),
	Station("LGN", "Longton"),
	Station("LGO", "Llangynllo"),
	Station("LGS", "Langside"),
	Station("LGW", "Langwathby"),
	Station("LHA", "Loch Awe"),
	Station("LHD", "Leatherhead"),
	Station("LHE", "Loch Eil Outward Bound"),
	Station("LHM", "Lealholm"),
	Station("LHO", "Langho"),
	Station("LHS", "Limehouse"),
	Station("LHW", "Lochwinnoch"),
	Station("LIC", "Lichfield City"),
	Station("LID", "Lidlington"),
	Station("LIH", "Leigh (Kent)"),
	Station("LIN", "Linlithgow"),
	Station("LIP", "Liphook"),
	Station("LIS", "Liss"),
	Station("LIT", "Littlehampton"),
	Station("LIV", "Liverpool Lime Street"),
	Station("LIV", "Liverpool Lime Street Ll"),
	Station("LKE", "Lake"),
	Station("LLA", "Llanaber"),
	Station("LLC", "Llandecwyn"),
	Station("LLD", "Llandudno"),
	Station("LLE", "Llanelli"),
	Station("LLF", "Llanfairfechan"),
	Station("LLG", "Llangadog"),
	Station("LLH", "Llangennech"),
	Station("LLI", "Llandybie"),
	Station("LLJ", "Llandudno Junction"),
	Station("LLL", "Llandeilo"),
	Station("LLM", "Llangammarch"),
	Station("LLN", "Llandaf"),
	Station("LLO", "Llandrindod"),
	Station("LLR", "Llanharan"),
	Station("LLS", "Llanishen"),
	Station("LLT", "Llanbister Road"),
	Station("LLV", "Llandovery"),
	Station("LLW", "Llwyngwril"),
	Station("LLY", "Llwynypia"),
	Station("LMR", "Low Moor"),
	Station("LMS", "Leamington Spa"),
	Station("LNB", "Llanbradach"),
	Station("LND", "Longniddry"),
	Station("LNG", "Longcross"),
	Station("LNK", "Lanark"),
	Station("LNR", "Llanwrda"),
	Station("LNW", "Llanwrtyd"),
	Station("LNY", "Langley (Berkshire)"),
	Station("LNZ", "Lenzie"),
	Station("LOB", "Longbridge"),
	Station("LOC", "Lockerbie"),
	Station("LOF", "London Fields"),
	Station("LOH", "Lostock Hall"),
	Station("LOO", "Looe"),
	Station("LOS", "Lostwithiel"),
	Station("LOT", "Lostock"),
	Station("LOW", "Lowdham"),
	Station("LPG", "Llanfairpwll"),
	Station("LPR", "Long Preston"),
	Station("LPT", "Longport"),
	Station("LPW", "Lapworth"),
	Station("LPY", "Liverpool South Parkway Hl"),
	Station("LPY", "Liverpool South Parkway"),
	Station("LRB", "London Road (Brighton)"),
	Station("LRD", "London Road (Guildford)"),
	Station("LRG", "Lairg"),
	Station("LRH", "Larkhall"),
	Station("LSK", "Liskeard"),
	Station("LSN", "Livingston North"),
	Station("LST", "London Liverpool Street"),
	Station("LSW", "Leasowe"),
	Station("LSY", "Lower Sydenham"),
	Station("LTG", "Lostock Gralam"),
	Station("LTH", "Llanhilleth"),
	Station("LTK", "Little Kimble"),
	Station("LTL", "Littleborough"),
	Station("LTM", "Lytham"),
	Station("LTN", "Luton Airport Parkway"),
	Station("LTP", "Littleport"),
	Station("LTR", "Lampeter Black Lion"),
	Station("LTS", "Lelant Saltings"),
	Station("LTT", "Little Sutton"),
	Station("LTV", "Lichfield Trent Valley Hl"),
	Station("LTV", "Lichfield Trent Valley"),
	Station("LUA", "Luton Airport"),
	Station("LUD", "Ludlow"),
	Station("LUT", "Luton"),
	Station("LUX", "Luxulyan"),
	Station("LVC", "Liverpool Central"),
	Station("LVC", "Liverpool Central"),
	Station("LVG", "Livingston South"),
	Station("LVJ", "Liverpool James Street"),
	Station("LVM", "Levenshulme"),
	Station("LVN", "Littlehaven"),
	Station("LVT", "Lisvane & Thornhill"),
	Station("LWH", "Lawrence Hill"),
	Station("LWM", "Llantwit Major"),
	Station("LWR", "Llanrwst"),
	Station("LWS", "Lewes"),
	Station("LWT", "Lowestoft"),
	Station("LYC", "Lympstone Commando"),
	Station("LYD", "Lydney"),
	Station("LYE", "Lye"),
	Station("LYM", "Lympstone Village"),
	Station("LYP", "Lymington Pier"),
	Station("LYT", "Lymington Town"),
	Station("LZB", "Lazonby & Kirkoswald"),
	Station("MAC", "Macclesfield"),
	Station("MAG", "Maghull"),
	Station("MAI", "Maidenhead"),
	Station("MAL", "Malden Manor"),
	Station("MAN", "Manchester Piccadilly"),
	Station("MAO", "Martins Heron"),
	Station("MAR", "Margate"),
	Station("MAS", "Manors"),
	Station("MAT", "Matlock"),
	Station("MAU", "Mauldeth Road"),
	Station("MAX", "Maxwell Park"),
	Station("MAY", "Maybole"),
	Station("MBK", "Millbrook (Hampshire)"),
	Station("MBR", "Middlesbrough"),
	Station("MBT", "Marsh Barton"),
	Station("MCB", "Moulsecoomb"),
	Station("MCE", "Metrocentre"),
	Station("MCH", "March"),
	Station("MCM", "Morecambe"),
	Station("MCN", "Machynlleth"),
	Station("MCO", "Manchester Oxford Road"),
	Station("MCV", "Manchester Victoria"),
	Station("MDB", "Maidstone Barracks"),
	Station("MDE", "Maidstone East"),
	Station("MDG", "Midgham"),
	Station("MDL", "Middlewood"),
	Station("MDN", "Maiden Newton"),
	Station("MDS", "Morden South"),
	Station("MDW", "Maidstone West"),
	Station("MEC", "Meols Cop"),
	Station("MEL", "Meldreth"),
	Station("MEN", "Menheniot"),
	Station("MEO", "Meols"),
	Station("MEP", "Meopham"),
	Station("MER", "Merthyr Tydfil"),
	Station("MES", "Melton (Suffolk)"),
	Station("MEV", "Merthyr Vale"),
	Station("MEW", "Maesteg (Ewenny Road)"),
	Station("MEX", "Mexborough"),
	Station("MEY", "Merryton"),
	Station("MFA", "Morfa Mawddach"),
	Station("MFF", "Minffordd"),
	Station("MFH", "Milford Haven"),
	Station("MFL", "Mount Florida"),
	Station("MFT", "Mansfield"),
	Station("MGM", "Metheringham"),
	Station("MGN", "Marston Green"),
	Station("MHM", "Merstham"),
	Station("MHR", "Market Harborough"),
	Station("MHS", "Meadowhall"),
	Station("MIA", "Manchester Airport"),
	Station("MIC", "Micheldever"),
	Station("MIH", "Mills Hill (Manchester)"),
	Station("MIJ", "Mitcham Junction"),
	Station("MIK", "Micklefield"),
	Station("MIL", "Mill Hill Broadway"),
	Station("MIM", "Moreton-in-Marsh"),
	Station("MIN", "Milliken Park"),
	Station("MIR", "Mirfield"),
	Station("MIS", "Mistley"),
	Station("MKC", "Milton Keynes Central"),
	Station("MKM", "Melksham"),
	Station("MKR", "Market Rasen"),
	Station("MKT", "Marks Tey"),
	Station("MLB", "Millbrook (Bedfordshire)"),
	Station("MLD", "Mouldsworth"),
	Station("MLF", "Milford (Surrey)"),
	Station("MLG", "Mallaig"),
	Station("MLH", "Mill Hill (Lancashire)"),
	Station("MLM", "Millom"),
	Station("MLN", "Milngavie"),
	Station("MLT", "Malton"),
	Station("MLW", "Marlow"),
	Station("MLY", "Morley"),
	Station("MMO", "Melton Mowbray"),
	Station("MNC", "Markinch"),
	Station("MNE", "Manea"),
	Station("MNG", "Manningtree"),
	Station("MNN", "Menston"),
	Station("MNP", "Manor Park"),
	Station("MNR", "Manor Road"),
	Station("MNS", "Maghull North"),
	Station("MOB", "Mobberley"),
	Station("MOG", "Moorgate"),
	Station("MON", "Monifieth"),
	Station("MOO", "Muir of Ord"),
	Station("MOR", "Mortimer"),
	Station("MOS", "Moss Side"),
	Station("MOT", "Motspur Park"),
	Station("MPK", "Mosspark"),
	Station("MPL", "Marple"),
	Station("MPT", "Morpeth"),
	Station("MRB", "Manorbier"),
	Station("MRD", "Morchard Road"),
	Station("MRF", "Moorfields"),
	Station("MRF", "Moorfields"),
	Station("MRN", "Marden"),
	Station("MRP", "Moorthorpe"),
	Station("MRR", "Morar"),
	Station("MRS", "Monks Risborough"),
	Station("MRT", "Moreton (Merseyside)"),
	Station("MRW", "Meridian Water"),
	Station("MRY", "Maryport"),
	Station("MSD", "Moorside"),
	Station("MSH", "Mossley Hill"),
	Station("MSK", "Marske"),
	Station("MSL", "Mossley (Manchester)"),
	Station("MSN", "Marsden (Yorks)"),
	Station("MSO", "Moston"),
	Station("MSR", "Minster"),
	Station("MSS", "Moses Gate"),
	Station("MST", "Maesteg"),
	Station("MSW", "Mansfield Woodhouse"),
	Station("MTA", "Mountain Ash"),
	Station("MTB", "Matlock Bath"),
	Station("MTC", "Mitcham Eastfields"),
	Station("MTG", "Mottingham"),
	Station("MTH", "Motherwell"),
	Station("MTL", "Mortlake"),
	Station("MTM", "Martin Mill"),
	Station("MTN", "Moreton (Dorset)"),
	Station("MTO", "Marton"),
	Station("MTP", "Montpelier"),
	Station("MTS", "Montrose"),
	Station("MTV", "Mount Vernon"),
	Station("MUB", "Musselburgh"),
	Station("MUF", "Manchester United Football"),
	Station("MUI", "Muirend"),
	Station("MVL", "Malvern Link"),
	Station("MYB", "London Marylebone"),
	Station("MYH", "Maryhill"),
	Station("MYL", "Maryland"),
	Station("MYT", "Mytholmroyd"),
	Station("MZH", "Maze Hill"),
	Station("NAN", "Nantwich"),
	Station("NAR", "Narberth"),
	Station("NAY", "Newton Aycliffe"),
	Station("NBA", "New Barnet"),
	Station("NBC", "New Beckenham"),
	Station("NBE", "Newbridge"),
	Station("NBN", "New Brighton"),
	Station("NBR", "Narborough"),
	Station("NBT", "Norbiton"),
	Station("NBW", "North Berwick"),
	Station("NBY", "Newbury"),
	Station("NCE", "New Clee"),
	Station("NCK", "New Cumnock"),
	Station("NCL", "Newcastle"),
	Station("NCM", "North Camp"),
	Station("NCO", "Newcourt"),
	Station("NCT", "Newark Castle"),
	Station("NDL", "North Dulwich"),
	Station("NEG", "Newtongrange"),
	Station("NEH", "New Eltham"),
	Station("NEI", "Neilston"),
	Station("NEL", "Nelson"),
	Station("NEM", "New Malden"),
	Station("NES", "Neston"),
	Station("NET", "Netherfield"),
	Station("NEW", "Newcraighall"),
	Station("NFA", "North Fambridge"),
	Station("NFD", "Northfield"),
	Station("NFL", "Northfleet"),
	Station("NFN", "Nafferton"),
	Station("NGT", "Newington"),
	Station("NHD", "Nunhead"),
	Station("NHE", "New Hythe"),
	Station("NHL", "New Holland"),
	Station("NIT", "Nitshill"),
	Station("NLN", "New Lane"),
	Station("NLR", "North Llanrwst"),
	Station("NLS", "Nailsea & Backwell"),
	Station("NLT", "Northolt Park"),
	Station("NLW", "Newton-le-Willows"),
	Station("NMC", "New Mills Central"),
	Station("NMK", "Newmarket"),
	Station("NMN", "New Mills Newtown"),
	Station("NMP", "Northampton"),
	Station("NMT", "Needham Market"),
	Station("NNG", "Newark Northgate"),
	Station("NNP", "Ninian Park"),
	Station("NNT", "Nunthorpe"),
	Station("NOA", "Newton-on-Ayr"),
	Station("NOR", "Normanton"),
	Station("NOT", "Nottingham"),
	Station("NPD", "New Pudsey"),
	Station("NQU", "North Queensferry"),
	Station("NQY", "Newquay"),
	Station("NRB", "Norbury"),
	Station("NRC", "Newbury Racecourse"),
	Station("NRD", "North Road (Darlington)"),
	Station("NRN", "Nairn"),
	Station("NRT", "Nethertown"),
	Station("NRW", "Norwich"),
	Station("NSB", "Normans Bay"),
	Station("NSD", "Newstead"),
	Station("NSG", "New Southgate"),
	Station("NSH", "North Sheen"),
	Station("NTA", "Newton Abbot"),
	Station("NTC", "Newton St Cyres"),
	Station("NTH", "Neath"),
	Station("NTL", "Netley"),
	Station("NTN", "Newton (Lanarkshire)"),
	Station("NTR", "Northallerton"),
	Station("NUF", "Nutfield"),
	Station("NUM", "Northumberland Park (Londo"),
	Station("NUN", "Nuneaton"),
	Station("NUT", "Nutbourne"),
	Station("NUT", "Nutbourne"),
	Station("NVH", "Newhaven Harbour"),
	Station("NVN", "Newhaven Town"),
	Station("NVR", "Navigation Road"),
	Station("NWA", "North Walsham"),
	Station("NWB", "North Wembley"),
	Station("NWD", "Norwood Junction"),
	Station("NWE", "Newport (Essex)"),
	Station("NWI", "Northwich"),
	Station("NWM", "New Milton"),
	Station("NWN", "Newton for Hyde"),
	Station("NWP", "Newport (South Wales)"),
	Station("NWR", "Newtonmore"),
	Station("NWT", "Newtown (Powys)"),
	Station("NWX", "New Cross"),
	Station("NXG", "New Cross Gate"),
	Station("OBN", "Oban"),
	Station("OCK", "Ockendon"),
	Station("OHL", "Old Hill"),
	Station("OKE", "Okehampton"),
	Station("OKL", "Oakleigh Park"),
	Station("OKM", "Oakham"),
	Station("OKN", "Oakengates"),
	Station("OLD", "Old Street"),
	Station("OLF", "Oldfield Park"),
	Station("OLT", "Olton"),
	Station("OLY", "Ockley"),
	Station("OMS", "Ormskirk"),
	Station("OPK", "Orrell Park"),
	Station("ORE", "Ore"),
	Station("ORN", "Old Roan"),
	Station("ORP", "Orpington"),
	Station("ORR", "Orrell"),
	Station("OTF", "Otford"),
	Station("OUN", "Oulton Broad North"),
	Station("OUS", "Oulton Broad South"),
	Station("OUT", "Outwood"),
	Station("OVE", "Overpool"),
	Station("OVR", "Overton"),
	Station("OXF", "Oxford"),
	Station("OXN", "Oxenholme Lake District"),
	Station("OXP", "Oxford Parkway"),
	Station("OXS", "Oxshott"),
	Station("OXT", "Oxted"),
	Station("OXT", "Oxted"),
	Station("PAD", "Paddington El"),
	Station("PAD", "London Paddington"),
	Station("PAL", "Palmers Green"),
	Station("PAN", "Pangbourne"),
	Station("PAR", "Par"),
	Station("PAT", "Patricroft"),
	Station("PBL", "Parbold"),
	Station("PBO", "Peterborough"),
	Station("PBR", "Potters Bar"),
	Station("PBY", "Pembrey & Burry Port"),
	Station("PCD", "Pencoed"),
	Station("PCN", "Paisley Canal"),
	Station("PDG", "Padgate"),
	Station("PDT", "Padstow Bus"),
	Station("PDW", "Paddock Wood"),
	Station("PEA", "Peartree"),
	Station("PEB", "Pevensey Bay"),
	Station("PEG", "Pegswood"),
	Station("PEM", "Pemberton"),
	Station("PEN", "Penarth"),
	Station("PER", "Penrhiwceiber"),
	Station("PES", "Pensarn (Gwynedd)"),
	Station("PET", "Petts Wood"),
	Station("PEV", "Pevensey & Westham"),
	Station("PEW", "Pewsey"),
	Station("PFL", "Purfleet"),
	Station("PFM", "Pontefract Monkhill"),
	Station("PFR", "Pontefract Baghill"),
	Station("PFY", "Poulton-le-Fylde"),
	Station("PGM", "Pengam"),
	Station("PGN", "Paignton"),
	Station("PHG", "Penhelig"),
	Station("PHR", "Penshurst"),
	Station("PIL", "Pilning"),
	Station("PIN", "Pinhoe"),
	Station("PIT", "Pitlochry"),
	Station("PIZ", "Pickering Bus"),
	Station("PKG", "Penkridge"),
	Station("PKS", "Parkstone (Dorset)"),
	Station("PKT", "Park Street"),
	Station("PLC", "Pluckley"),
	Station("PLD", "Portslade"),
	Station("PLE", "Pollokshields East"),
	Station("PLG", "Polegate"),
	Station("PLK", "Plockton"),
	Station("PLM", "Plumley"),
	Station("PLN", "Portlethen"),
	Station("PLS", "Pleasington"),
	Station("PLT", "Pontlottyn"),
	Station("PLU", "Plumstead"),
	Station("PLW", "Pollokshields West"),
	Station("PLY", "Plymouth"),
	Station("PMA", "Portsmouth Arms"),
	Station("PMB", "Pembroke"),
	Station("PMD", "Pembroke Dock"),
	Station("PMH", "Portsmouth Harbour"),
	Station("PMP", "Plumpton"),
	Station("PMR", "Peckham Rye"),
	Station("PMR", "Peckham Rye"),
	Station("PMS", "Portsmouth & Southsea"),
	Station("PMT", "Polmont"),
	Station("PMW", "Penmaenmawr"),
	Station("PNA", "Penally"),
	Station("PNC", "Penychain"),
	Station("PNE", "Penge East"),
	Station("PNF", "Penyffordd"),
	Station("PNL", "Pannal"),
	Station("PNM", "Penmere"),
	Station("PNR", "Penrith North Lakes"),
	Station("PNS", "Penistone"),
	Station("PNW", "Penge West"),
	Station("PNY", "Pen-y-Bont"),
	Station("PNZ", "Penzance"),
	Station("POK", "Pokesdown"),
	Station("POL", "Polsloe Bridge"),
	Station("PON", "Ponders End"),
	Station("POO", "Poole"),
	Station("POP", "Poppleton"),
	Station("POR", "Porth"),
	Station("POT", "Pontefract Tanshelf"),
	Station("PPD", "Pontypridd"),
	Station("PPK", "Possilpark & Parkhouse"),
	Station("PPL", "Pontypool & New Inn"),
	Station("PRA", "Prestwick Intl Airport"),
	Station("PRB", "Prestbury"),
	Station("PRE", "Preston"),
	Station("PRH", "Penrhyndeudraeth"),
	Station("PRI", "Portway Park & Ride"),
	Station("PRL", "Prittlewell"),
	Station("PRN", "Parton"),
	Station("PRP", "Preston Park"),
	Station("PRR", "Princes Risborough"),
	Station("PRS", "Prees"),
	Station("PRT", "Prestatyn"),
	Station("PRU", "Prudhoe"),
	Station("PRW", "Perranwell"),
	Station("PRY", "Perry Barr"),
	Station("PSC", "Prescot"),
	Station("PSE", "Pitsea"),
	Station("PSH", "Pershore"),
	Station("PSL", "Port Sunlight"),
	Station("PSN", "Parson Street"),
	Station("PST", "Prestonpans"),
	Station("PSW", "Polesworth"),
	Station("PTA", "Port Talbot Parkway"),
	Station("PTB", "Pentre-Bach"),
	Station("PTC", "Portchester"),
	Station("PTD", "Pontarddulais"),
	Station("PTF", "Pantyffynnon"),
	Station("PTG", "Port Glasgow"),
	Station("PTH", "Perth"),
	Station("PTK", "Partick"),
	Station("PTL", "Priesthill & Darnley"),
	Station("PTM", "Porthmadog"),
	Station("PTR", "Petersfield"),
	Station("PTT", "Patterton"),
	Station("PTW", "Prestwick Town"),
	Station("PUL", "Pulborough"),
	Station("PUO", "Purley Oaks"),
	Station("PUR", "Purley"),
	Station("PUT", "Putney"),
	Station("PWE", "Pollokshaws East"),
	Station("PWL", "Pwllheli"),
	Station("PWW", "Pollokshaws West"),
	Station("PWY", "Patchway"),
	Station("PYC", "Pontyclun"),
	Station("PYE", "Pye Corner"),
	Station("PYG", "Paisley Gilmour Street"),
	Station("PYJ", "Paisley St James"),
	Station("PYL", "Pyle"),
	Station("PYN", "Penryn"),
	Station("PYP", "Pont-y-Pant"),
	Station("PYT", "Poynton"),
	Station("QBR", "Queenborough"),
	Station("QPK", "Queens Park (Glasgow)"),
	Station("QPW", "Queens Park (London)"),
	Station("QRB", "Queenstown Road (Battersea"),
	Station("QRP", "Queens Road Peckham"),
	Station("QUI", "Quintrell Downs"),
	Station("QYD", "Quakers Yard"),
	Station("RAD", "Radley"),
	Station("RAI", "Rainham (Kent)"),
	Station("RAM", "Ramsgate"),
	Station("RAN", "Rannoch"),
	Station("RAU", "Rauceby"),
	Station("RAV", "Ravenglass for Eskdale"),
	Station("RAY", "Raynes Park"),
	Station("RBR", "Robertsbridge"),
	Station("RCA", "Risca & Pontymister"),
	Station("RCC", "Redcar Central"),
	Station("RCD", "Rochdale"),
	Station("RCE", "Redcar East"),
	Station("RDA", "Redland"),
	Station("RDB", "Redbridge"),
	Station("RDC", "Redditch"),
	Station("RDD", "Riddlesdown"),
	Station("RDF", "Radcliffe (Nottinghamshire"),
	Station("RDG", "Reading 4/5/6"),
	Station("RDG", "Reading"),
	Station("RDH", "Redhill"),
	Station("RDM", "Riding Mill"),
	Station("RDN", "Reddish North"),
	Station("RDR", "Radyr"),
	Station("RDS", "Reddish South"),
	Station("RDT", "Radlett"),
	Station("RDW", "Reading West"),
	Station("REC", "Rectory Road"),
	Station("RED", "Redruth"),
	Station("REE", "Reedham (Norfolk)"),
	Station("REI", "Reigate"),
	Station("RET", "Retford"),
	Station("RET", "Retford Low Level"),
	Station("RFD", "Rochford"),
	Station("RFY", "Rock Ferry"),
	Station("RGL", "Rugeley Trent Valley"),
	Station("RGP", "Reading Green Park"),
	Station("RGT", "Rugeley Town"),
	Station("RGW", "Ramsgreave & Wilpshire"),
	Station("RHD", "Ribblehead"),
	Station("RHI", "Rhiwbina"),
	Station("RHL", "Rhyl"),
	Station("RHM", "Reedham (London)"),
	Station("RHO", "Rhosneigr"),
	Station("RHY", "Rhymney"),
	Station("RIA", "Rhoose Cardiff Intl Airpor"),
	Station("RIC", "Rickmansworth"),
	Station("RID", "Ridgmont"),
	Station("RIL", "Rice Lane"),
	Station("RIS", "Rishton"),
	Station("RKT", "Ruskington"),
	Station("RLG", "Rayleigh"),
	Station("RLN", "Rowlands Castle"),
	Station("RMB", "Roman Bridge"),
	Station("RMC", "Rotherham Central"),
	Station("RMD", "Richmond (London)"),
	Station("RMD", "Richmond (Surrey)"),
	Station("RMF", "Romford"),
	Station("RML", "Romiley"),
	Station("RNF", "Rainford"),
	Station("RNH", "Rainhill"),
	Station("RNM", "Rainham (Essex)"),
	Station("RNR", "Roughton Road"),
	Station("ROB", "Roby"),
	Station("ROC", "Roche"),
	Station("ROE", "Rotherhithe"),
	Station("ROG", "Rogart"),
	Station("ROL", "Rolleston"),
	Station("ROM", "Romsey"),
	Station("ROO", "Roose"),
	Station("ROR", "Rogerstone"),
	Station("ROS", "Rosyth"),
	Station("ROW", "Rowley Regis"),
	Station("RRB", "Ryder Brow"),
	Station("RRN", "Robroyston"),
	Station("RSG", "Rose Grove"),
	Station("RSH", "Rose Hill Marple"),
	Station("RSN", "Reston"),
	Station("RTN", "Renton"),
	Station("RTR", "Rochester"),
	Station("RUA", "Ruabon"),
	Station("RUE", "Runcorn East"),
	Station("RUF", "Rufford"),
	Station("RUG", "Rugby"),
	Station("RUN", "Runcorn"),
	Station("RUS", "Ruswarp"),
	Station("RUT", "Rutherglen"),
	Station("RVB", "Ravensbourne"),
	Station("RVN", "Ravensthorpe"),
	Station("RWC", "Rawcliffe"),
	Station("RYB", "Roy Bridge"),
	Station("RYD", "Ryde Esplanade"),
	Station("RYE", "Rye"),
	Station("RYH", "Rye House"),
	Station("RYN", "Roydon"),
	Station("RYP", "Ryde Pier Head"),
	Station("RYR", "Ryde St Johns Road"),
	Station("RYS", "Royston"),
	Station("SAA", "St Albans Abbey"),
	Station("SAB", "Smallbrook Junction"),
	Station("SAC", "St Albans City"),
	Station("SAD", "Sandwell & Dudley"),
	Station("SAE", "Saltaire"),
	Station("SAF", "Salfords (Surrey)"),
	Station("SAH", "Salhouse"),
	Station("SAJ", "St Johns (London)"),
	Station("SAL", "Salisbury"),
	Station("SAM", "Saltmarshe"),
	Station("SAN", "Sandown"),
	Station("SAO", "St Andrews Bus"),
	Station("SAR", "St Andrews Road"),
	Station("SAS", "St Annes-on-the-Sea"),
	Station("SAT", "South Acton"),
	Station("SAU", "St Austell"),
	Station("SAV", "Stratford-upon-Avon"),
	Station("SAW", "Sawbridgeworth"),
	Station("SAX", "Saxmundham"),
	Station("SAY", "Swanley"),
	Station("SBE", "Starbeck"),
	Station("SBF", "St Budeaux Ferry Road"),
	Station("SBJ", "Stourbridge Junction"),
	Station("SBK", "South Bank"),
	Station("SBM", "South Bermondsey"),
	Station("SBP", "Stonebridge Park"),
	Station("SBR", "Spean Bridge"),
	Station("SBS", "St Bees"),
	Station("SBT", "Stourbridge Town"),
	Station("SBU", "Southbury"),
	Station("SBV", "St Budeaux Victoria Road"),
	Station("SBY", "Selby"),
	Station("SCA", "Scarborough"),
	Station("SCF", "Stechford"),
	Station("SCG", "Stone Crossing"),
	Station("SCH", "Scotstounhill"),
	Station("SCN", "Stone Crown St"),
	Station("SCR", "St Columb Road"),
	Station("SCS", "Starcross"),
	Station("SCT", "Scotscalder"),
	Station("SCU", "Scunthorpe"),
	Station("SCY", "South Croydon"),
	Station("SDA", "Snodland"),
	Station("SDB", "Sandbach"),
	Station("SDC", "Shoreditch High Street"),
	Station("SDE", "Shadwell"),
	Station("SDF", "Saundersfoot"),
	Station("SDG", "Sandling"),
	Station("SDH", "Sudbury Hill Harrow"),
	Station("SDL", "Sandhills"),
	Station("SDM", "Shieldmuir"),
	Station("SDN", "St Denys"),
	Station("SDP", "Sandplace"),
	Station("SDR", "Saunderton"),
	Station("SDW", "Sandwich"),
	Station("SDY", "Sandy"),
	Station("SEA", "Seaham"),
	Station("SEB", "Seaburn"),
	Station("SEC", "Seaton Carew"),
	Station("SED", "Shelford (Cambridgeshire)"),
	Station("SEE", "Southease"),
	Station("SEF", "Seaford"),
	Station("SEG", "Selling"),
	Station("SEH", "Shoreham (Kent)"),
	Station("SEL", "Sellafield"),
	Station("SEM", "Seamer"),
	Station("SEN", "Shenstone"),
	Station("SER", "St Erth"),
	Station("SES", "South Elmsall"),
	Station("SET", "Settle"),
	Station("SEV", "Sevenoaks"),
	Station("SEZ", "Southease Church"),
	Station("SFA", "Stratford International"),
	Station("SFA", "Stratford International"),
	Station("SFD", "Salford Central"),
	Station("SFI", "Shawfair"),
	Station("SFL", "Seaforth & Litherland"),
	Station("SFN", "Shifnal"),
	Station("SFO", "Stanford-le-Hope"),
	Station("SFR", "Shalford (Surrey)"),
	Station("SGB", "Smethwick Galton Bridge"),
	Station("SGB", "Smethwick Galton Bridge"),
	Station("SGE", "Swanage"),
	Station("SGL", "South Gyle"),
	Station("SGM", "St Germans"),
	Station("SGN", "South Greenford"),
	Station("SGQ", "Stone Grnvle Sq"),
	Station("SGR", "Slade Green"),
	Station("SHB", "Shirebrook"),
	Station("SHC", "Streethouse"),
	Station("SHD", "Shildon"),
	Station("SHE", "Sherborne"),
	Station("SHF", "Sheffield"),
	Station("SHH", "Shirehampton"),
	Station("SHI", "Shiplake"),
	Station("SHJ", "St Helens Junction"),
	Station("SHL", "Shawlands"),
	Station("SHM", "Sheringham"),
	Station("SHN", "Shanklin"),
	Station("SHO", "Sholing"),
	Station("SHP", "Shepperton"),
	Station("SHR", "Shrewsbury"),
	Station("SHS", "Shotts"),
	Station("SHT", "Shotton"),
	Station("SHT", "Shotton"),
	Station("SHU", "Stonehouse"),
	Station("SHU", "Stonehouse"),
	Station("SHV", "Southsea Hoverport"),
	Station("SHW", "Shawford"),
	Station("SHY", "Shipley"),
	Station("SIA", "Southend Airport"),
	Station("SIC", "Silecroft"),
	Station("SID", "Sidcup"),
	Station("SIE", "Sherburn-in-Elmet"),
	Station("SIH", "St Helier (London)"),
	Station("SIL", "Sileby"),
	Station("SIN", "Singer"),
	Station("SIP", "Shipton"),
	Station("SIT", "Sittingbourne"),
	Station("SIV", "St Ives (Cornwall)"),
	Station("SJP", "St James Park (Exeter)"),
	Station("SJS", "St James Street (Walthamst"),
	Station("SKE", "Skewen"),
	Station("SKG", "Skegness"),
	Station("SKI", "Skipton"),
	Station("SKM", "Stoke Mandeville"),
	Station("SKN", "St Keyne Wishing Well Halt"),
	Station("SKS", "Stocksfield"),
	Station("SKW", "Stoke Newington"),
	Station("SLA", "Slateford"),
	Station("SLB", "Saltburn"),
	Station("SLD", "Salford Crescent"),
	Station("SLH", "Sleights"),
	Station("SLK", "Silkstone Common"),
	Station("SLL", "Stallingborough"),
	Station("SLO", "Slough"),
	Station("SLQ", "St Leonards Warrior Square"),
	Station("SLR", "Sleaford"),
	Station("SLS", "Shettleston"),
	Station("SLT", "Saltcoats"),
	Station("SLV", "Silver Street"),
	Station("SLW", "Salwick"),
	Station("SLY", "Selly Oak"),
	Station("SMA", "Small Heath"),
	Station("SMB", "Smithy Bridge"),
	Station("SMD", "Stamford"),
	Station("SMG", "St Margarets (London)"),
	Station("SMH", "Stamford Hill"),
	Station("SMK", "Stowmarket"),
	Station("SML", "Sea Mills"),
	Station("SMN", "Southminster"),
	Station("SMO", "South Merton"),
	Station("SMR", "Smethwick Rolfe Street"),
	Station("SMT", "St Margarets (Hertfordshir"),
	Station("SMY", "St Mary Cray"),
	Station("SNA", "Sandal & Agbrigg"),
	Station("SND", "Sandhurst (Berkshire)"),
	Station("SNE", "Stone (Staffs)"),
	Station("SNF", "Shenfield"),
	Station("SNG", "Sunningdale"),
	Station("SNH", "St Helens Central"),
	Station("SNI", "Snaith"),
	Station("SNK", "Sankey for Penketh"),
	Station("SNL", "Stoneleigh"),
	Station("SNN", "Swinton (Manchester)"),
	Station("SNO", "St Neots"),
	Station("SNR", "Sanderstead"),
	Station("SNS", "Staines"),
	Station("SNT", "Stanlow & Thornton"),
	Station("SNW", "Swanwick"),
	Station("SNY", "Sunnymeads"),
	Station("SOA", "Southampton Airport Parkwa"),
	Station("SOB", "Southbourne"),
	Station("SOC", "Southend Central"),
	Station("SOE", "Southend East"),
	Station("SOF", "South Woodham Ferrers"),
	Station("SOG", "Stonegate"),
	Station("SOH", "South Hampstead"),
	Station("SOI", "Stow"),
	Station("SOJ", "Soham"),
	Station("SOK", "South Kenton"),
	Station("SOL", "Solihull"),
	Station("SOM", "South Milford"),
	Station("SON", "Steeton & Silsden"),
	Station("SOO", "Strood (Kent)"),
	Station("SOP", "Southport"),
	Station("SOR", "Sole Street"),
	Station("SOT", "Stoke-on-Trent"),
	Station("SOU", "Southampton Central"),
	Station("SOV", "Southend Victoria"),
	Station("SOW", "Sowerby Bridge"),
	Station("SPA", "Spalding"),
	Station("SPB", "Shepherds Bush"),
	Station("SPF", "Springfield"),
	Station("SPH", "Shepherds Well"),
	Station("SPI", "Spital"),
	Station("SPK", "Sutton Parkway"),
	Station("SPN", "Spooner Row"),
	Station("SPO", "Spondon"),
	Station("SPP", "Shippea Hill"),
	Station("SPR", "Springburn"),
	Station("SPS", "Stepps"),
	Station("SPT", "Stockport"),
	Station("SPU", "Staplehurst"),
	Station("SPY", "Shepley"),
	Station("SQE", "Surrey Quays"),
	Station("SQH", "Sanquhar"),
	Station("SQU", "Squires Gate"),
	Station("SRA", "Stratford (London)"),
	Station("SRC", "Streatham Common"),
	Station("SRD", "Stapleton Road"),
	Station("SRG", "Seer Green & Jordans"),
	Station("SRH", "Streatham Hill"),
	Station("SRI", "Spring Road"),
	Station("SRL", "Shirley"),
	Station("SRN", "Strines"),
	Station("SRO", "Shireoaks"),
	Station("SRR", "Sarn"),
	Station("SRS", "Selhurst"),
	Station("SRT", "Shortlands"),
	Station("SRU", "South Ruislip"),
	Station("SRY", "Shoeburyness"),
	Station("SSA", "Southease A26"),
	Station("SSC", "Seascale"),
	Station("SSD", "Stansted Airport"),
	Station("SSE", "Shoreham-by-Sea"),
	Station("SSM", "Stocksmoor"),
	Station("SSS", "Sheerness-on-Sea"),
	Station("SST", "Stansted Mountfitchet"),
	Station("STA", "Stafford"),
	Station("STC", "Strathcarron"),
	Station("STD", "Stroud (Glos)"),
	Station("STE", "Streatham"),
	Station("STF", "Stromeferry"),
	Station("STG", "Stirling"),
	Station("STH", "Shepreth"),
	Station("STI", "Stadium Of Light"),
	Station("STJ", "Severn Tunnel Junction"),
	Station("STK", "Stockton"),
	Station("STL", "Southall"),
	Station("STM", "St Michaels"),
	Station("STN", "Stonehaven"),
	Station("STO", "South Tottenham"),
	Station("STP", "London St Pancras"),
	Station("STR", "Stranraer"),
	Station("STS", "Saltash"),
	Station("STT", "Stewarton"),
	Station("STU", "Sturry"),
	Station("STV", "Stevenston"),
	Station("STW", "Strawberry Hill"),
	Station("STY", "Stratford-Upon-Avon Parkwa"),
	Station("STZ", "St Peters"),
	Station("SUC", "Sutton Common"),
	Station("SUD", "Sudbury & Harrow Road"),
	Station("SUG", "Sugar Loaf"),
	Station("SUM", "Summerston"),
	Station("SUN", "Sunderland"),
	Station("SUO", "Sutton (London)"),
	Station("SUP", "Sundridge Park"),
	Station("SUR", "Surbiton"),
	Station("SUT", "Sutton Coldfield"),
	Station("SUU", "Sunbury"),
	Station("SUY", "Sudbury (Suffolk)"),
	Station("SVB", "Severn Beach"),
	Station("SVG", "Stevenage"),
	Station("SVK", "Seven Kings"),
	Station("SVL", "Staveley"),
	Station("SVR", "Silverdale"),
	Station("SVS", "Seven Sisters"),
	Station("SWA", "Swansea"),
	Station("SWB", "Swaffham (Coach)"),
	Station("SWD", "Swinderby"),
	Station("SWE", "Swineshead"),
	Station("SWG", "Swaythling"),
	Station("SWI", "Swindon (Wilts)"),
	Station("SWK", "Southwick"),
	Station("SWL", "Swale"),
	Station("SWM", "Swanscombe"),
	Station("SWN", "Swinton (South Yorkshire)"),
	Station("SWO", "Snowdown"),
	Station("SWR", "Stewartby"),
	Station("SWS", "South Wigston"),
	Station("SWT", "Slaithwaite"),
	Station("SWY", "Sway"),
	Station("SXY", "Saxilby"),
	Station("SYA", "Styal"),
	Station("SYB", "Stalybridge"),
	Station("SYD", "Sydenham"),
	Station("SYH", "Sydenham Hill"),
	Station("SYL", "Syon Lane"),
	Station("SYS", "Syston"),
	Station("SYT", "Somerleyton"),
	Station("TAB", "Tame Bridge Parkway"),
	Station("TAC", "Tackley"),
	Station("TAD", "Tadworth"),
	Station("TAF", "Taffs Well"),
	Station("TAI", "Tain"),
	Station("TAL", "Talsarnau"),
	Station("TAM", "Tamworth Hl"),
	Station("TAM", "Tamworth"),
	Station("TAP", "Taplow"),
	Station("TAT", "Tattenham Corner"),
	Station("TAU", "Taunton"),
	Station("TAY", "Taynuilt"),
	Station("TBD", "Three Bridges"),
	Station("TBR", "Tilbury Riverside"),
	Station("TBW", "Tunbridge Wells"),
	Station("TBY", "Thornaby"),
	Station("TCR", "Tottenham Court Road El"),
	Station("TDU", "Tondu"),
	Station("TEA", "Teesside Airport"),
	Station("TED", "Teddington"),
	Station("TEN", "Tenby"),
	Station("TEO", "Theobalds Grove"),
	Station("TEY", "Teynham"),
	Station("TFC", "Telford Central"),
	Station("TGM", "Teignmouth"),
	Station("TGS", "Ty Glas"),
	Station("THA", "Thatcham"),
	Station("THB", "Thornliebank"),
	Station("THC", "Thurnscoe"),
	Station("THD", "Thames Ditton"),
	Station("THE", "Theale"),
	Station("THH", "Thatto Heath"),
	Station("THI", "Thirsk"),
	Station("THL", "Tile Hill"),
	Station("THO", "Thornford"),
	Station("THP", "Thanet Parkway"),
	Station("THS", "Thurso"),
	Station("THT", "Thorntonhall"),
	Station("THU", "Thurgarton"),
	Station("THW", "The Hawthorns"),
	Station("TIL", "Tilbury Town"),
	Station("TIP", "Tipton"),
	Station("TIR", "Tir-Phil"),
	Station("TIS", "Tisbury"),
	Station("TLB", "Talybont"),
	Station("TLC", "Tal-y-Cafn"),
	Station("TLH", "Tilehurst"),
	Station("TLK", "The Lakes (Warwickshire)"),
	Station("TLS", "Thorpe-le-Soken"),
	Station("TMC", "Templecombe"),
	Station("TNA", "Thornton Abbey"),
	Station("TNF", "Tonfanau"),
	Station("TNN", "Thorne North"),
	Station("TNP", "Tonypandy"),
	Station("TNS", "Thorne South"),
	Station("TOD", "Todmorden"),
	Station("TOK", "Three Oaks"),
	Station("TOK", "Three Oaks"),
	Station("TOL", "Tolworth"),
	Station("TOM", "Tottenham Hale"),
	Station("TON", "Tonbridge"),
	Station("TOO", "Tooting"),
	Station("TOP", "Topsham"),
	Station("TOT", "Totnes"),
	Station("TPB", "Thorpe Bay"),
	Station("TPC", "Thorpe Culvert"),
	Station("TPN", "Ton Pentre"),
	Station("TQY", "Torquay"),
	Station("TRA", "Trafford Park"),
	Station("TRB", "Treherbert"),
	Station("TRD", "Troed-y-Rhiw"),
	Station("TRE", "Trefforest Estate"),
	Station("TRF", "Trefforest"),
	Station("TRH", "Trehafod"),
	Station("TRI", "Tring"),
	Station("TRM", "Trimley"),
	Station("TRN", "Troon"),
	Station("TRO", "Trowbridge"),
	Station("TRR", "Torre"),
	Station("TRS", "Thurston"),
	Station("TRU", "Truro"),
	Station("TRY", "Treorchy"),
	Station("TTA", "Tadworth (Avenue"),
	Station("TTF", "Thetford"),
	Station("TTH", "Thornton Heath"),
	Station("TTN", "Totton"),
	Station("TUH", "Tulse Hill"),
	Station("TUL", "Tulloch"),
	Station("TUR", "Turkey Street"),
	Station("TUT", "Tutbury & Hatton"),
	Station("TVP", "Tiverton Parkway"),
	Station("TWB", "Tweedbank"),
	Station("TWI", "Twickenham"),
	Station("TWN", "Town Green"),
	Station("TWY", "Twyford"),
	Station("TYC", "Ty Croes"),
	Station("TYG", "Tygwyn"),
	Station("TYL", "Tyndrum Lower"),
	Station("TYS", "Tyseley"),
	Station("TYW", "Tywyn"),
	Station("UCK", "Uckfield"),
	Station("UDD", "Uddingston"),
	Station("UHA", "Uphall"),
	Station("UHL", "Upper Holloway"),
	Station("ULC", "Ulceby"),
	Station("ULL", "Ulleskelf"),
	Station("ULV", "Ulverston"),
	Station("UMB", "Umberleigh"),
	Station("UNI", "University (Birmingham)"),
	Station("UPH", "Upper Halliford"),
	Station("UPL", "Upholland"),
	Station("UPM", "Upminster"),
	Station("UPM", "Upminster"),
	Station("UPT", "Upton"),
	Station("UPW", "Upwey"),
	Station("URM", "Urmston"),
	Station("UTT", "Uttoxeter"),
	Station("UTY", "Upper Tyndrum"),
	Station("UWL", "Upper Warlingham"),
	Station("VAL", "Valley"),
	Station("VIC", "London Victoria"),
	Station("VIC", "London Victoria"),
	Station("VIR", "Virginia Water"),
	Station("VXH", "Vauxhall"),
	Station("WAC", "Warrington Central"),
	Station("WAD", "Wadhurst"),
	Station("WAE", "London Waterloo East"),
	Station("WAF", "Wallyford"),
	Station("WAL", "Walton-on-Thames"),
	Station("WAM", "Walmer"),
	Station("WAN", "Wanborough"),
	Station("WAO", "Walton (Merseyside)"),
	Station("WAR", "Ware"),
	Station("WAS", "Watton-at-Stone"),
	Station("WAT", "London Waterloo"),
	Station("WAV", "Wavertree Technology Park"),
	Station("WAW", "Warrington West"),
	Station("WBC", "Waterbeach"),
	Station("WBD", "Whitley Bridge"),
	Station("WBE", "Wadebridge Bus"),
	Station("WBL", "Warblington"),
	Station("WBO", "Wimbledon Chase"),
	Station("WBP", "West Brompton"),
	Station("WBQ", "Warrington Bank Quay"),
	Station("WBR", "Whaley Bridge"),
	Station("WBY", "West Byfleet"),
	Station("WCB", "Westcombe Park"),
	Station("WCF", "Westcliff"),
	Station("WCH", "Whitchurch (Hampshire)"),
	Station("WCK", "Wick"),
	Station("WCL", "West Calder"),
	Station("WCM", "Wickham Market"),
	Station("WCP", "Worcester Park"),
	Station("WCR", "Whitecraigs"),
	Station("WCX", "Wembley Stadium"),
	Station("WCY", "West Croydon"),
	Station("WDB", "Woodbridge"),
	Station("WDD", "Widdrington"),
	Station("WDE", "Wood End"),
	Station("WDH", "Woodhouse"),
	Station("WDL", "Woodhall"),
	Station("WDM", "Windermere"),
	Station("WDN", "Walsden"),
	Station("WDO", "Waddon"),
	Station("WDS", "Woodlesford"),
	Station("WDT", "West Drayton"),
	Station("WDU", "West Dulwich"),
	Station("WDU", "West Dulwich"),
	Station("WEA", "West Ealing"),
	Station("WED", "Wedgwood"),
	Station("WEE", "Weeley"),
	Station("WEH", "West Ham"),
	Station("WEL", "Wellingborough"),
	Station("WEM", "Wem"),
	Station("WES", "Westerton"),
	Station("WET", "Weeton"),
	Station("WEY", "Weymouth"),
	Station("WFF", "Whifflet"),
	Station("WFH", "Watford High Street"),
	Station("WFI", "Westerfield"),
	Station("WFJ", "Watford Junction"),
	Station("WFJ", "Watford Junction"),
	Station("WFL", "Wainfleet"),
	Station("WFN", "Watford North"),
	Station("WGA", "Westgate-on-Sea"),
	Station("WGC", "Welwyn Garden City"),
	Station("WGN", "Wigan North Western"),
	Station("WGR", "Woodgrange Park"),
	Station("WGT", "Wigton"),
	Station("WGV", "Wargrave"),
	Station("WGW", "Wigan Wallgate"),
	Station("WHA", "Westenhanger"),
	Station("WHC", "Walthamstow Central"),
	Station("WHD", "West Hampstead"),
	Station("WHE", "Whalley"),
	Station("WHG", "Westhoughton"),
	Station("WHI", "Whitstable"),
	Station("WHL", "White Hart Lane"),
	Station("WHM", "Whimple"),
	Station("WHN", "Whiston"),
	Station("WHP", "West Hampstead Thameslink"),
	Station("WHR", "West Horndon"),
	Station("WHS", "Whyteleafe South"),
	Station("WHT", "Whitchurch (Cardiff)"),
	Station("WHY", "Whyteleafe"),
	Station("WIC", "Wickford"),
	Station("WID", "Widnes"),
	Station("WIH", "Winchmore Hill"),
	Station("WIJ", "Willesden Junction"),
	Station("WIJ", "Willesden Junction"),
	Station("WIJ", "Willesden Junction"),
	Station("WIJ", "Willesden Junction"),
	Station("WIL", "Willington"),
	Station("WIM", "Wimbledon"),
	Station("WIM", "Wimbledon"),
	Station("WIN", "Winchester"),
	Station("WIR", "Wirksworth"),
	Station("WIV", "Wivenhoe"),
	Station("WKB", "West Kilbride"),
	Station("WKD", "Walkden"),
	Station("WKF", "Wakefield Westgate"),
	Station("WKG", "Workington"),
	Station("WKI", "West Kirby"),
	Station("WKK", "Wakefield Kirkgate"),
	Station("WKM", "Wokingham"),
	Station("WLC", "Waltham Cross"),
	Station("WLD", "West St Leonards"),
	Station("WLE", "Whittlesea"),
	Station("WLF", "Whittlesford Parkway"),
	Station("WLG", "Wallasey Grove Road"),
	Station("WLI", "Welling"),
	Station("WLM", "Williamwood"),
	Station("WLN", "Wellington (Shropshire)"),
	Station("WLO", "Waterloo (Merseyside)"),
	Station("WLP", "Welshpool"),
	Station("WLS", "Woolston"),
	Station("WLT", "Wallington"),
	Station("WLV", "Wallasey Village"),
	Station("WLW", "Welwyn North"),
	Station("WLY", "Woodley"),
	Station("WMA", "West Malling"),
	Station("WMB", "Wembley Central"),
	Station("WMB", "Wembley Central"),
	Station("WMC", "Wilmcote (Warwickshire)"),
	Station("WMD", "Wymondham"),
	Station("WME", "Woodmansterne"),
	Station("WMG", "Welham Green"),
	Station("WMI", "Wildmill"),
	Station("WML", "Wilmslow"),
	Station("WMN", "Warminster"),
	Station("WMR", "Widney Manor"),
	Station("WMS", "Wemyss Bay"),
	Station("WMW", "Walthamstow Queens Road"),
	Station("WNC", "Windsor & Eton Central"),
	Station("WND", "Wendover"),
	Station("WNE", "Wilnecote (Staffordshire)"),
	Station("WNF", "Winchfield"),
	Station("WNG", "Waun-Gron Park"),
	Station("WNH", "Warnham"),
	Station("WNL", "Whinhill"),
	Station("WNM", "Weston Milton"),
	Station("WNN", "Wennington"),
	Station("WNP", "Wanstead Park"),
	Station("WNR", "Windsor & Eton Riverside"),
	Station("WNS", "Winnersh"),
	Station("WNT", "Wandsworth Town"),
	Station("WNW", "West Norwood"),
	Station("WNY", "White Notley"),
	Station("WOB", "Woburn Sands"),
	Station("WOF", "Worcester Foregate Street"),
	Station("WOH", "Woldingham"),
	Station("WOK", "Woking"),
	Station("WOL", "Wolverton"),
	Station("WOM", "Wombwell"),
	Station("WON", "Walton-On-The-Naze"),
	Station("WOO", "Wool"),
	Station("WOP", "Worcestershire Parkway Hl"),
	Station("WOP", "Worcestershire Parkway"),
	Station("WOR", "Worle"),
	Station("WOS", "Worcester Shrub Hill"),
	Station("WPE", "Wapping"),
	Station("WPL", "Worplesdon"),
	Station("WRB", "Wrabness"),
	Station("WRE", "Wrenbury"),
	Station("WRH", "Worthing"),
	Station("WRK", "Worksop"),
	Station("WRL", "Wetheral"),
	Station("WRM", "Wareham"),
	Station("WRN", "West Runton"),
	Station("WRP", "Warwick Parkway"),
	Station("WRS", "Wressle"),
	Station("WRT", "Worstead"),
	Station("WRU", "West Ruislip"),
	Station("WRW", "Warwick"),
	Station("WRX", "Wrexham General"),
	Station("WRY", "Wraysbury"),
	Station("WSA", "West Allerton"),
	Station("WSB", "Westbury"),
	Station("WSE", "Winchelsea"),
	Station("WSF", "Winsford"),
	Station("WSH", "Wishaw"),
	Station("WSL", "Walsall"),
	Station("WSM", "Weston-super-Mare"),
	Station("WSR", "Woodsmoor"),
	Station("WST", "Wood Street"),
	Station("WSU", "West Sutton"),
	Station("WSW", "Wandsworth Common"),
	Station("WTA", "Westerhailes"),
	Station("WTB", "Whitby"),
	Station("WTC", "Whitchurch (Shropshire)"),
	Station("WTE", "Whitlocks End"),
	Station("WTG", "Watlington"),
	Station("WTH", "Whitehaven"),
	Station("WTI", "Winnersh Triangle"),
	Station("WTL", "Whitland"),
	Station("WTM", "Witham"),
	Station("WTN", "Whitton (London)"),
	Station("WTO", "Water Orton"),
	Station("WTR", "Wateringbury"),
	Station("WTS", "Whatstandwell"),
	Station("WTT", "Witton (West Midlands)"),
	Station("WTY", "Witley"),
	Station("WTZ", "Whitby Bus"),
	Station("WVF", "Wivelsfield"),
	Station("WVH", "Wolverhampton"),
	Station("WWA", "Woolwich Arsenal"),
	Station("WWC", "Woolwich El"),
	Station("WWD", "Woolwich Dockyard"),
	Station("WWI", "West Wickham"),
	Station("WWL", "Whitwell"),
	Station("WWO", "West Worthing"),
	Station("WWR", "Wandsworth Road"),
	Station("WWW", "Wootton Wawen"),
	Station("WXC", "Wrexham Central"),
	Station("WYB", "Weybridge"),
	Station("WYB", "Weybridge"),
	Station("WYE", "Wye"),
	Station("WYL", "Wylde Green"),
	Station("WYM", "Wylam"),
	Station("WYT", "Wythall"),
	Station("XAA", "Galashiels V Bwk"),
	Station("XAQ", "Devizes Bus"),
	Station("XAV", "Helston Bus"),
	Station("XBR", "Midsomer Ntn Bus"),
	Station("XBW", "Minehead Bus"),
	Station("XBW", "Minehead Bus"),
	Station("XCF", "Cardiff Air Ria"),
	Station("XCG", "Okehampton Bus"),
	Station("XCG", "Okehampton Bus"),
	Station("XDY", "Dunster Bus"),
	Station("XEA", "Glastonbury Bus"),
	Station("XEE", "Holsworthy Bus"),
	Station("XEE", "Holsworthy Bus"),
	Station("XEF", "Mevagissey Bus"),
	Station("XLB", "Leeds Brd Airbus"),
	Station("XPB", "Bristol Airport"),
	Station("XPB", "Bristol Air Bus"),
	Station("XRD", "Ryde Hoverport"),
	Station("XSO", "Southwold Bus"),
	Station("YAE", "Yate"),
	Station("YAL", "Yalding"),
	Station("YAT", "Yatton"),
	Station("YEO", "Yeoford"),
	Station("YET", "Yetminster"),
	Station("YMH", "Yarmouth Iow"),
	Station("YNW", "Ynyswen"),
	Station("YOK", "Yoker"),
	Station("YRD", "Yardley Wood"),
	Station("YRK", "York"),
	Station("YRM", "Yarm"),
	Station("YRT", "Yorton"),
	Station("YSM", "Ystrad Mynach"),
	Station("YSR", "Ystrad Rhondda"),
	Station("YVJ", "Yeovil Junction"),
	Station("YVP", "Yeovil Pen Mill"),
	Station("ZBB", "Barbican"),
	Station("ZBD", "Bond Street Und"),
	Station("ZBS", "Baker Street Und"),
	Station("ZCW", "Canada Water"),
	Station("ZET", "Earl's Court L.T."),
	Station("ZFD", "Farringdon"),
	Station("ZFD", "Farringdon El"),
	Station("ZLW", "Whitechapel"),
	Station("ZLW", "Whitechapel El"),
	Station("ZNP", "Newbury Park Und"),
)
